// DO NOT EDIT: this file is automatically generated by docgen
package metalcloud

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var (
	DriveArrayDoc          encoder.Doc
	DriveArrayOperationDoc encoder.Doc
)

func init() {
	DriveArrayDoc.Type = "DriveArray"
	DriveArrayDoc.Comments[encoder.LineComment] = "DriveArray represents a collection of identical drives"
	DriveArrayDoc.Description = "DriveArray represents a collection of identical drives"
	DriveArrayDoc.Fields = make([]encoder.Doc, 14)
	DriveArrayDoc.Fields[0].Name = "id"
	DriveArrayDoc.Fields[0].Type = "int"
	DriveArrayDoc.Fields[0].Note = ""
	DriveArrayDoc.Fields[0].Description = "The id of the object"
	DriveArrayDoc.Fields[0].Comments[encoder.LineComment] = "The id of the object"
	DriveArrayDoc.Fields[1].Name = "label"
	DriveArrayDoc.Fields[1].Type = "string"
	DriveArrayDoc.Fields[1].Note = ""
	DriveArrayDoc.Fields[1].Description = "The label of the object"
	DriveArrayDoc.Fields[1].Comments[encoder.LineComment] = "The label of the object"
	DriveArrayDoc.Fields[2].Name = "volumeTemplateID"
	DriveArrayDoc.Fields[2].Type = "int"
	DriveArrayDoc.Fields[2].Note = ""
	DriveArrayDoc.Fields[2].Description = "When the drive array is used with images (such as for diskless boot) this field will keep the Volume Template ID of template to use."
	DriveArrayDoc.Fields[2].Comments[encoder.LineComment] = "When the drive array is used with images (such as for diskless boot) this field will keep the Volume Template ID of template to use."
	DriveArrayDoc.Fields[3].Name = "storageType"
	DriveArrayDoc.Fields[3].Type = "string"
	DriveArrayDoc.Fields[3].Note = ""
	DriveArrayDoc.Fields[3].Description = "What type of storage to use. This string needs to match the type of storage exported by a storage pool"
	DriveArrayDoc.Fields[3].Comments[encoder.LineComment] = "What type of storage to use. This string needs to match the type of storage exported by a storage pool"
	DriveArrayDoc.Fields[4].Name = "sizeMBytesDefault"
	DriveArrayDoc.Fields[4].Type = "int"
	DriveArrayDoc.Fields[4].Note = ""
	DriveArrayDoc.Fields[4].Description = "The size of the volume. Note that this value is used when creating the drive array but also when expanding the drive array (increasing the count)."
	DriveArrayDoc.Fields[4].Comments[encoder.LineComment] = "The size of the volume. Note that this value is used when creating the drive array but also when expanding the drive array (increasing the count)."
	DriveArrayDoc.Fields[5].Name = "instanceArrayID"
	DriveArrayDoc.Fields[5].Type = "int"
	DriveArrayDoc.Fields[5].Note = ""
	DriveArrayDoc.Fields[5].Description = "The ID of the instance array to which this drive array is connected. Can be 0 if not connected."
	DriveArrayDoc.Fields[5].Comments[encoder.LineComment] = "The ID of the instance array to which this drive array is connected. Can be 0 if not connected."
	DriveArrayDoc.Fields[6].Name = "infrastructureID"
	DriveArrayDoc.Fields[6].Type = "int"
	DriveArrayDoc.Fields[6].Note = ""
	DriveArrayDoc.Fields[6].Description = "The ID of the infrastructure to which this drive array belongs."
	DriveArrayDoc.Fields[6].Comments[encoder.LineComment] = "The ID of the infrastructure to which this drive array belongs."
	DriveArrayDoc.Fields[7].Name = "serviceStatus"
	DriveArrayDoc.Fields[7].Type = "string"
	DriveArrayDoc.Fields[7].Note = ""
	DriveArrayDoc.Fields[7].Description = "The ID of the infrastructure to which this drive array belongs."
	DriveArrayDoc.Fields[7].Comments[encoder.LineComment] = "The ID of the infrastructure to which this drive array belongs."
	DriveArrayDoc.Fields[8].Name = "count"
	DriveArrayDoc.Fields[8].Type = "int"
	DriveArrayDoc.Fields[8].Note = ""
	DriveArrayDoc.Fields[8].Description = "The number of drives in this drive array."
	DriveArrayDoc.Fields[8].Comments[encoder.LineComment] = "The number of drives in this drive array."
	DriveArrayDoc.Fields[9].Name = "expandWithInstanceArray"
	DriveArrayDoc.Fields[9].Type = "bool"
	DriveArrayDoc.Fields[9].Note = ""
	DriveArrayDoc.Fields[9].Description = "If set to true the number of drives in the drive array will expand if the attached instance array expands (instance count increases)."
	DriveArrayDoc.Fields[9].Comments[encoder.LineComment] = "If set to true the number of drives in the drive array will expand if the attached instance array expands (instance count increases)."
	DriveArrayDoc.Fields[10].Name = "operation"
	DriveArrayDoc.Fields[10].Type = "DriveArrayOperation"
	DriveArrayDoc.Fields[10].Note = ""
	DriveArrayDoc.Fields[10].Description = "Operation object of the drive array"
	DriveArrayDoc.Fields[10].Comments[encoder.LineComment] = "Operation object of the drive array"
	DriveArrayDoc.Fields[11].Name = "ioLimit"
	DriveArrayDoc.Fields[11].Type = "string"
	DriveArrayDoc.Fields[11].Note = ""
	DriveArrayDoc.Fields[11].Description = "Only valid for certain storage systems (such as Dell Unity)."
	DriveArrayDoc.Fields[11].Comments[encoder.LineComment] = "Only valid for certain storage systems (such as Dell Unity)."
	DriveArrayDoc.Fields[12].Name = "storagePoolID"
	DriveArrayDoc.Fields[12].Type = "int"
	DriveArrayDoc.Fields[12].Note = ""
	DriveArrayDoc.Fields[12].Description = "If set the specified storage pool will be used to allocate the drive instead of automatic allocation."
	DriveArrayDoc.Fields[12].Comments[encoder.LineComment] = "If set the specified storage pool will be used to allocate the drive instead of automatic allocation."
	DriveArrayDoc.Fields[13].Name = "affinity"
	DriveArrayDoc.Fields[13].Type = "string"
	DriveArrayDoc.Fields[13].Note = ""
	DriveArrayDoc.Fields[13].Description = "Used to control if drives in this drive array should be allocated on the same storage pool or different storage pools"
	DriveArrayDoc.Fields[13].Comments[encoder.LineComment] = "Used to control if drives in this drive array should be allocated on the same storage pool or different storage pools"
	DriveArrayDoc.Fields[13].Values = []string{
		"same_storage",
		"different_storage",
	}

	DriveArrayOperationDoc.Type = "DriveArrayOperation"
	DriveArrayOperationDoc.Comments[encoder.LineComment] = "DriveArrayOperation defines changes to be applied to a DriveArray"
	DriveArrayOperationDoc.Description = "DriveArrayOperation defines changes to be applied to a DriveArray"
	DriveArrayOperationDoc.AppearsIn = []encoder.Appearance{
		{
			TypeName:  "DriveArray",
			FieldName: "operation",
		},
	}
	DriveArrayOperationDoc.Fields = make([]encoder.Doc, 15)
	DriveArrayOperationDoc.Fields[0].Name = "id"
	DriveArrayOperationDoc.Fields[0].Type = "int"
	DriveArrayOperationDoc.Fields[0].Note = ""
	DriveArrayOperationDoc.Fields[0].Description = "The id of the object"
	DriveArrayOperationDoc.Fields[0].Comments[encoder.LineComment] = "The id of the object"
	DriveArrayOperationDoc.Fields[1].Name = "label"
	DriveArrayOperationDoc.Fields[1].Type = "string"
	DriveArrayOperationDoc.Fields[1].Note = ""
	DriveArrayOperationDoc.Fields[1].Description = "The label of the object"
	DriveArrayOperationDoc.Fields[1].Comments[encoder.LineComment] = "The label of the object"
	DriveArrayOperationDoc.Fields[2].Name = "volumeTemplateID"
	DriveArrayOperationDoc.Fields[2].Type = "int"
	DriveArrayOperationDoc.Fields[2].Note = ""
	DriveArrayOperationDoc.Fields[2].Description = "When the drive array is used with images (such as for diskless boot) this field will keep the Volume Template ID of template to use."
	DriveArrayOperationDoc.Fields[2].Comments[encoder.LineComment] = "When the drive array is used with images (such as for diskless boot) this field will keep the Volume Template ID of template to use."
	DriveArrayOperationDoc.Fields[3].Name = "storageType"
	DriveArrayOperationDoc.Fields[3].Type = "string"
	DriveArrayOperationDoc.Fields[3].Note = ""
	DriveArrayOperationDoc.Fields[3].Description = "What type of storage to use. This string needs to match the type of storage exported by a storage pool"
	DriveArrayOperationDoc.Fields[3].Comments[encoder.LineComment] = "What type of storage to use. This string needs to match the type of storage exported by a storage pool"
	DriveArrayOperationDoc.Fields[4].Name = "sizeMBytes"
	DriveArrayOperationDoc.Fields[4].Type = "int"
	DriveArrayOperationDoc.Fields[4].Note = ""
	DriveArrayOperationDoc.Fields[4].Description = "The size of the volume. Note that this value is used when creating the drive array but also when expanding the drive array (increasing the count)."
	DriveArrayOperationDoc.Fields[4].Comments[encoder.LineComment] = "The size of the volume. Note that this value is used when creating the drive array but also when expanding the drive array (increasing the count)."
	DriveArrayOperationDoc.Fields[5].Name = "instanceArrayID"
	DriveArrayOperationDoc.Fields[5].Type = "interface{}"
	DriveArrayOperationDoc.Fields[5].Note = ""
	DriveArrayOperationDoc.Fields[5].Description = "The ID of the instance array to which this drive array is connected. Can be 0 if not connected."
	DriveArrayOperationDoc.Fields[5].Comments[encoder.LineComment] = "The ID of the instance array to which this drive array is connected. Can be 0 if not connected."
	DriveArrayOperationDoc.Fields[6].Name = "infrastructureID"
	DriveArrayOperationDoc.Fields[6].Type = "int"
	DriveArrayOperationDoc.Fields[6].Note = ""
	DriveArrayOperationDoc.Fields[6].Description = "The ID of the infrastructure to which this drive array belongs."
	DriveArrayOperationDoc.Fields[6].Comments[encoder.LineComment] = "The ID of the infrastructure to which this drive array belongs."
	DriveArrayOperationDoc.Fields[7].Name = "count"
	DriveArrayOperationDoc.Fields[7].Type = "int"
	DriveArrayOperationDoc.Fields[7].Note = ""
	DriveArrayOperationDoc.Fields[7].Description = "The ID of the infrastructure to which this drive array belongs."
	DriveArrayOperationDoc.Fields[7].Comments[encoder.LineComment] = "The ID of the infrastructure to which this drive array belongs."
	DriveArrayOperationDoc.Fields[8].Name = "expandWithInstanceArray"
	DriveArrayOperationDoc.Fields[8].Type = "bool"
	DriveArrayOperationDoc.Fields[8].Note = ""
	DriveArrayOperationDoc.Fields[8].Description = "If set to true the number of drives in the drive array will expand if the attached instance array expands (instance count increases)."
	DriveArrayOperationDoc.Fields[8].Comments[encoder.LineComment] = "If set to true the number of drives in the drive array will expand if the attached instance array expands (instance count increases)."
	DriveArrayOperationDoc.Fields[9].Name = "deployType"
	DriveArrayOperationDoc.Fields[9].Type = "string"
	DriveArrayOperationDoc.Fields[9].Note = ""
	DriveArrayOperationDoc.Fields[9].Description = "description: The deploy type\nvalues:\n    - create\n	   - delete\n    - edit\n	   - start\n    - stop\n	   - suspend\n"
	DriveArrayOperationDoc.Fields[9].Comments[encoder.LineComment] = "description: The deploy type"
	DriveArrayOperationDoc.Fields[10].Name = "deployStatus"
	DriveArrayOperationDoc.Fields[10].Type = "string"
	DriveArrayOperationDoc.Fields[10].Note = ""
	DriveArrayOperationDoc.Fields[10].Description = "The status of the deployment"
	DriveArrayOperationDoc.Fields[10].Comments[encoder.LineComment] = "The status of the deployment"
	DriveArrayOperationDoc.Fields[10].Values = []string{
		"not_started",
		"ongoing",
		"finished",
	}
	DriveArrayOperationDoc.Fields[11].Name = "changeID"
	DriveArrayOperationDoc.Fields[11].Type = "int"
	DriveArrayOperationDoc.Fields[11].Note = ""
	DriveArrayOperationDoc.Fields[11].Description = "The id of the change operation. Readonly."
	DriveArrayOperationDoc.Fields[11].Comments[encoder.LineComment] = "The id of the change operation. Readonly."
	DriveArrayOperationDoc.Fields[12].Name = "ioLimit"
	DriveArrayOperationDoc.Fields[12].Type = "string"
	DriveArrayOperationDoc.Fields[12].Note = ""
	DriveArrayOperationDoc.Fields[12].Description = "Only valid for certain storage systems (such as Dell Unity)."
	DriveArrayOperationDoc.Fields[12].Comments[encoder.LineComment] = "Only valid for certain storage systems (such as Dell Unity)."
	DriveArrayOperationDoc.Fields[13].Name = "storagePoolID"
	DriveArrayOperationDoc.Fields[13].Type = "int"
	DriveArrayOperationDoc.Fields[13].Note = ""
	DriveArrayOperationDoc.Fields[13].Description = "If set the specified storage pool will be used to allocate the drive instead of automatic allocation."
	DriveArrayOperationDoc.Fields[13].Comments[encoder.LineComment] = "If set the specified storage pool will be used to allocate the drive instead of automatic allocation."
	DriveArrayOperationDoc.Fields[14].Name = "affinity"
	DriveArrayOperationDoc.Fields[14].Type = "string"
	DriveArrayOperationDoc.Fields[14].Note = ""
	DriveArrayOperationDoc.Fields[14].Description = "Used to control if drives in this drive array should be allocated on the same storage pool or different storage pools"
	DriveArrayOperationDoc.Fields[14].Comments[encoder.LineComment] = "Used to control if drives in this drive array should be allocated on the same storage pool or different storage pools"
	DriveArrayOperationDoc.Fields[14].Values = []string{
		"same_storage",
		"different_storage",
	}
}

func (DriveArray) Doc() *encoder.Doc {
	return &DriveArrayDoc
}

func (DriveArrayOperation) Doc() *encoder.Doc {
	return &DriveArrayOperationDoc
}

// GetDriveArrayDoc returns documentation for the file ./.
func GetDriveArrayDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "DriveArray",
		Description: "",
		Structs: []*encoder.Doc{
			&DriveArrayDoc,
			&DriveArrayOperationDoc,
		},
	}
}
