// DO NOT EDIT: this file is automatically generated by docgen
package metalcloud

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var (
	InfrastructureDoc          encoder.Doc
	InfrastructureOperationDoc encoder.Doc
)

func init() {
	InfrastructureDoc.Type = "Infrastructure"
	InfrastructureDoc.Comments[encoder.LineComment] = "description - The infrastructure object. All other client-side objects (InstanceArrays, DriveArrays) fall under it in the object hierarchy"
	InfrastructureDoc.Description = "description - The infrastructure object. All other client-side objects (InstanceArrays, DriveArrays) fall under it in the object hierarchy"
	InfrastructureDoc.Fields = make([]encoder.Doc, 16)
	InfrastructureDoc.Fields[0].Name = "id"
	InfrastructureDoc.Fields[0].Type = "int"
	InfrastructureDoc.Fields[0].Note = ""
	InfrastructureDoc.Fields[0].Description = "The id of the object"
	InfrastructureDoc.Fields[0].Comments[encoder.LineComment] = "The id of the object"
	InfrastructureDoc.Fields[1].Name = "label"
	InfrastructureDoc.Fields[1].Type = "string"
	InfrastructureDoc.Fields[1].Note = ""
	InfrastructureDoc.Fields[1].Description = "The label of the object"
	InfrastructureDoc.Fields[1].Comments[encoder.LineComment] = "The label of the object"
	InfrastructureDoc.Fields[2].Name = "datacenter"
	InfrastructureDoc.Fields[2].Type = "string"
	InfrastructureDoc.Fields[2].Note = ""
	InfrastructureDoc.Fields[2].Description = "The datacenter label on which this infrastructure resides"
	InfrastructureDoc.Fields[2].Comments[encoder.LineComment] = "The datacenter label on which this infrastructure resides"
	InfrastructureDoc.Fields[3].Name = "subdomain"
	InfrastructureDoc.Fields[3].Type = "string"
	InfrastructureDoc.Fields[3].Note = ""
	InfrastructureDoc.Fields[3].Description = "An automatically generated string that represents this infrastructure. Deprecated."
	InfrastructureDoc.Fields[3].Comments[encoder.LineComment] = "An automatically generated string that represents this infrastructure. Deprecated."
	InfrastructureDoc.Fields[4].Name = "ownerID"
	InfrastructureDoc.Fields[4].Type = "int"
	InfrastructureDoc.Fields[4].Note = ""
	InfrastructureDoc.Fields[4].Description = "The ID of the user that is the owner of the infrastructure."
	InfrastructureDoc.Fields[4].Comments[encoder.LineComment] = "The ID of the user that is the owner of the infrastructure."
	InfrastructureDoc.Fields[5].Name = "ownerEmail"
	InfrastructureDoc.Fields[5].Type = "string"
	InfrastructureDoc.Fields[5].Note = ""
	InfrastructureDoc.Fields[5].Description = "The email of the user that is the owner of the infrastructure. Readonly"
	InfrastructureDoc.Fields[5].Comments[encoder.LineComment] = "The email of the user that is the owner of the infrastructure. Readonly"
	InfrastructureDoc.Fields[6].Name = "touchUnixTime"
	InfrastructureDoc.Fields[6].Type = "string"
	InfrastructureDoc.Fields[6].Note = ""
	InfrastructureDoc.Fields[6].Description = "Internal."
	InfrastructureDoc.Fields[6].Comments[encoder.LineComment] = "Internal."
	InfrastructureDoc.Fields[7].Name = "serviceStatus"
	InfrastructureDoc.Fields[7].Type = "string"
	InfrastructureDoc.Fields[7].Note = ""
	InfrastructureDoc.Fields[7].Description = "The service status.  Read only."
	InfrastructureDoc.Fields[7].Comments[encoder.LineComment] = "The service status.  Read only."
	InfrastructureDoc.Fields[7].Values = []string{
		"ordered",
		"active",
		"suspended",
		"stopped",
		"deleted",
	}
	InfrastructureDoc.Fields[8].Name = "createdTimestamp"
	InfrastructureDoc.Fields[8].Type = "string"
	InfrastructureDoc.Fields[8].Note = ""
	InfrastructureDoc.Fields[8].Description = "ISO 8601 timestamp which holds the date and time when the infrastructure was created."
	InfrastructureDoc.Fields[8].Comments[encoder.LineComment] = "ISO 8601 timestamp which holds the date and time when the infrastructure was created."
	InfrastructureDoc.Fields[9].Name = "updatedTimestamp"
	InfrastructureDoc.Fields[9].Type = "string"
	InfrastructureDoc.Fields[9].Note = ""
	InfrastructureDoc.Fields[9].Description = "ISO 8601 timestamp which holds the date and time when the infrastructure was last updated."
	InfrastructureDoc.Fields[9].Comments[encoder.LineComment] = "ISO 8601 timestamp which holds the date and time when the infrastructure was last updated."
	InfrastructureDoc.Fields[10].Name = "changeID"
	InfrastructureDoc.Fields[10].Type = "int"
	InfrastructureDoc.Fields[10].Note = ""
	InfrastructureDoc.Fields[10].Description = "The id of the ongoing change operation. readonly"
	InfrastructureDoc.Fields[10].Comments[encoder.LineComment] = "The id of the ongoing change operation. readonly"
	InfrastructureDoc.Fields[11].Name = "deployID"
	InfrastructureDoc.Fields[11].Type = "int"
	InfrastructureDoc.Fields[11].Note = ""
	InfrastructureDoc.Fields[11].Description = "The ID of the current deploy operation (AFC group id). Readonly."
	InfrastructureDoc.Fields[11].Comments[encoder.LineComment] = "The ID of the current deploy operation (AFC group id). Readonly."
	InfrastructureDoc.Fields[12].Name = "designIsLocked"
	InfrastructureDoc.Fields[12].Type = "bool"
	InfrastructureDoc.Fields[12].Note = ""
	InfrastructureDoc.Fields[12].Description = "Set if the infrastructure cannot be changed."
	InfrastructureDoc.Fields[12].Comments[encoder.LineComment] = "Set if the infrastructure cannot be changed."
	InfrastructureDoc.Fields[13].Name = "operation"
	InfrastructureDoc.Fields[13].Type = "InfrastructureOperation"
	InfrastructureDoc.Fields[13].Note = ""
	InfrastructureDoc.Fields[13].Description = "The operation object"
	InfrastructureDoc.Fields[13].Comments[encoder.LineComment] = "The operation object"
	InfrastructureDoc.Fields[14].Name = ""
	InfrastructureDoc.Fields[14].Type = "string"
	InfrastructureDoc.Fields[14].Note = ""
	InfrastructureDoc.Fields[14].Description = "Internal"
	InfrastructureDoc.Fields[14].Comments[encoder.LineComment] = "Internal"
	InfrastructureDoc.Fields[15].Name = "customVariables"
	InfrastructureDoc.Fields[15].Type = "interface{}"
	InfrastructureDoc.Fields[15].Note = ""
	InfrastructureDoc.Fields[15].Description = "Custom variables at the infrastructure level. They will be pushed to all objects (such as operating systems) and workflows."
	InfrastructureDoc.Fields[15].Comments[encoder.LineComment] = "Custom variables at the infrastructure level. They will be pushed to all objects (such as operating systems) and workflows."

	InfrastructureOperationDoc.Type = "InfrastructureOperation"
	InfrastructureOperationDoc.Comments[encoder.LineComment] = "InfrastructureOperation - object with alternations to be applied"
	InfrastructureOperationDoc.Description = "InfrastructureOperation - object with alternations to be applied"
	InfrastructureOperationDoc.AppearsIn = []encoder.Appearance{
		{
			TypeName:  "Infrastructure",
			FieldName: "operation",
		},
	}
	InfrastructureOperationDoc.Fields = make([]encoder.Doc, 11)
	InfrastructureOperationDoc.Fields[0].Name = "id"
	InfrastructureOperationDoc.Fields[0].Type = "int"
	InfrastructureOperationDoc.Fields[0].Note = ""
	InfrastructureOperationDoc.Fields[0].Description = "The id of the object"
	InfrastructureOperationDoc.Fields[0].Comments[encoder.LineComment] = "The id of the object"
	InfrastructureOperationDoc.Fields[1].Name = "label"
	InfrastructureOperationDoc.Fields[1].Type = "string"
	InfrastructureOperationDoc.Fields[1].Note = ""
	InfrastructureOperationDoc.Fields[1].Description = "The label of the object"
	InfrastructureOperationDoc.Fields[1].Comments[encoder.LineComment] = "The label of the object"
	InfrastructureOperationDoc.Fields[2].Name = "datacenter"
	InfrastructureOperationDoc.Fields[2].Type = "string"
	InfrastructureOperationDoc.Fields[2].Note = ""
	InfrastructureOperationDoc.Fields[2].Description = "The datacenter label on which this infrastructure resides"
	InfrastructureOperationDoc.Fields[2].Comments[encoder.LineComment] = "The datacenter label on which this infrastructure resides"
	InfrastructureOperationDoc.Fields[3].Name = "deployStatus"
	InfrastructureOperationDoc.Fields[3].Type = "string"
	InfrastructureOperationDoc.Fields[3].Note = ""
	InfrastructureOperationDoc.Fields[3].Description = "The status of the ongoing deployment operation (if any)"
	InfrastructureOperationDoc.Fields[3].Comments[encoder.LineComment] = "The status of the ongoing deployment operation (if any)"
	InfrastructureOperationDoc.Fields[3].Values = []string{
		"not_started",
		"ongoing",
		"finished",
	}
	InfrastructureOperationDoc.Fields[4].Name = "deployType"
	InfrastructureOperationDoc.Fields[4].Type = "string"
	InfrastructureOperationDoc.Fields[4].Note = ""
	InfrastructureOperationDoc.Fields[4].Description = "description: The type of the current deploy operation (if any)\nvalues:\n    - create\n	   - delete\n    - edit\n	   - start\n    - stop\n	   - suspend\n"
	InfrastructureOperationDoc.Fields[4].Comments[encoder.LineComment] = "description: The type of the current deploy operation (if any)"
	InfrastructureOperationDoc.Fields[5].Name = "subdomain"
	InfrastructureOperationDoc.Fields[5].Type = "string"
	InfrastructureOperationDoc.Fields[5].Note = ""
	InfrastructureOperationDoc.Fields[5].Description = "An automatically generated string that represents this infrastructure. Deprecated."
	InfrastructureOperationDoc.Fields[5].Comments[encoder.LineComment] = "An automatically generated string that represents this infrastructure. Deprecated."
	InfrastructureOperationDoc.Fields[6].Name = "ownerID"
	InfrastructureOperationDoc.Fields[6].Type = "int"
	InfrastructureOperationDoc.Fields[6].Note = ""
	InfrastructureOperationDoc.Fields[6].Description = "The ID of the user that is the owner of the infrastructure."
	InfrastructureOperationDoc.Fields[6].Comments[encoder.LineComment] = "The ID of the user that is the owner of the infrastructure."
	InfrastructureOperationDoc.Fields[7].Name = "updatedTimestamp"
	InfrastructureOperationDoc.Fields[7].Type = "string"
	InfrastructureOperationDoc.Fields[7].Note = ""
	InfrastructureOperationDoc.Fields[7].Description = "ISO 8601 timestamp which holds the date and time when the infrastructure was last updated."
	InfrastructureOperationDoc.Fields[7].Comments[encoder.LineComment] = "ISO 8601 timestamp which holds the date and time when the infrastructure was last updated."
	InfrastructureOperationDoc.Fields[8].Name = "changeID"
	InfrastructureOperationDoc.Fields[8].Type = "int"
	InfrastructureOperationDoc.Fields[8].Note = ""
	InfrastructureOperationDoc.Fields[8].Description = "The ID of the current change operation. Readonly."
	InfrastructureOperationDoc.Fields[8].Comments[encoder.LineComment] = "The ID of the current change operation. Readonly."
	InfrastructureOperationDoc.Fields[9].Name = "deployID"
	InfrastructureOperationDoc.Fields[9].Type = "int"
	InfrastructureOperationDoc.Fields[9].Note = ""
	InfrastructureOperationDoc.Fields[9].Description = "The ID of the current deploy operation (AFC group id). Readonly."
	InfrastructureOperationDoc.Fields[9].Comments[encoder.LineComment] = "The ID of the current deploy operation (AFC group id). Readonly."
	InfrastructureOperationDoc.Fields[10].Name = "customVariables"
	InfrastructureOperationDoc.Fields[10].Type = "interface{}"
	InfrastructureOperationDoc.Fields[10].Note = ""
	InfrastructureOperationDoc.Fields[10].Description = "Custom variables at the infrastructure level. They will be pushed to all objects (such as operating systems) and workflows."
	InfrastructureOperationDoc.Fields[10].Comments[encoder.LineComment] = "Custom variables at the infrastructure level. They will be pushed to all objects (such as operating systems) and workflows."
}

func (Infrastructure) Doc() *encoder.Doc {
	return &InfrastructureDoc
}

func (InfrastructureOperation) Doc() *encoder.Doc {
	return &InfrastructureOperationDoc
}

// GetInfrastructureDoc returns documentation for the file ./.
func GetInfrastructureDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "Infrastructure",
		Description: "",
		Structs: []*encoder.Doc{
			&InfrastructureDoc,
			&InfrastructureOperationDoc,
		},
	}
}
