// DO NOT EDIT: this file is automatically generated by docgen
package metalcloud

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var (
	InstanceArrayDoc                   encoder.Doc
	InstanceArrayOperationDoc          encoder.Doc
	InstanceArrayInterfaceDoc          encoder.Doc
	InstanceArrayInterfaceOperationDoc encoder.Doc
)

func init() {
	InstanceArrayDoc.Type = "InstanceArray"
	InstanceArrayDoc.Comments[encoder.LineComment] = "InstanceArray object describes a collection of identical instances"
	InstanceArrayDoc.Description = "InstanceArray object describes a collection of identical instances"
	InstanceArrayDoc.Fields = make([]encoder.Doc, 25)
	InstanceArrayDoc.Fields[0].Name = "instanceID"
	InstanceArrayDoc.Fields[0].Type = "int"
	InstanceArrayDoc.Fields[0].Note = ""
	InstanceArrayDoc.Fields[0].Description = "The ID of the object."
	InstanceArrayDoc.Fields[0].Comments[encoder.LineComment] = "The ID of the object."
	InstanceArrayDoc.Fields[1].Name = "label"
	InstanceArrayDoc.Fields[1].Type = "string"
	InstanceArrayDoc.Fields[1].Note = ""
	InstanceArrayDoc.Fields[1].Description = "description: The label of the object. Must be unique per infrastructure. Must follow DNS naming rules: Pattern: ^[a-zA-Z]{1,1}[a-zA-Z0-9-]{0,61}[a-zA-Z0-9]{1,1}|[a-zA-Z]{1,1}$"
	InstanceArrayDoc.Fields[1].Comments[encoder.LineComment] = "description: The label of the object. Must be unique per infrastructure. Must follow DNS naming rules: Pattern: ^[a-zA-Z]{1,1}[a-zA-Z0-9-]{0,61}[a-zA-Z0-9]{1,1}|[a-zA-Z]{1,1}$"
	InstanceArrayDoc.Fields[2].Name = "subdomain"
	InstanceArrayDoc.Fields[2].Type = "string"
	InstanceArrayDoc.Fields[2].Note = ""
	InstanceArrayDoc.Fields[2].Description = "description: |\n		User editable DNS record that gets created for this instance array in the built-in DNS\n		service and associated with all the primary IP address on the WAN network. Must adhere to DNS naming rules such\n     as:  only \"-\", lowercase alphanumeric characters and not start with a number.\n     Pattern:\n"
	InstanceArrayDoc.Fields[2].Comments[encoder.LineComment] = "description: |"
	InstanceArrayDoc.Fields[3].Name = "bootMethod"
	InstanceArrayDoc.Fields[3].Type = "string"
	InstanceArrayDoc.Fields[3].Note = ""
	InstanceArrayDoc.Fields[3].Description = "description: The booth method to use. Note that the pxe_iscsi booth method is deprecated.\nvalues:\n	- local_disks\n - pxe_iscsi\n"
	InstanceArrayDoc.Fields[3].Comments[encoder.LineComment] = "description: The booth method to use. Note that the pxe_iscsi booth method is deprecated."
	InstanceArrayDoc.Fields[4].Name = "instanceCount"
	InstanceArrayDoc.Fields[4].Type = "int"
	InstanceArrayDoc.Fields[4].Note = ""
	InstanceArrayDoc.Fields[4].Description = "The number of instances in this array."
	InstanceArrayDoc.Fields[4].Comments[encoder.LineComment] = "The number of instances in this array."
	InstanceArrayDoc.Fields[5].Name = "ramGBytes"
	InstanceArrayDoc.Fields[5].Type = "int"
	InstanceArrayDoc.Fields[5].Note = ""
	InstanceArrayDoc.Fields[5].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum amount of RAM expressed in GB."
	InstanceArrayDoc.Fields[5].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum amount of RAM expressed in GB."
	InstanceArrayDoc.Fields[6].Name = "processorCount"
	InstanceArrayDoc.Fields[6].Type = "int"
	InstanceArrayDoc.Fields[6].Note = ""
	InstanceArrayDoc.Fields[6].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum amount of CPU sockets."
	InstanceArrayDoc.Fields[6].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum amount of CPU sockets."
	InstanceArrayDoc.Fields[7].Name = "processorCoreMhz"
	InstanceArrayDoc.Fields[7].Type = "int"
	InstanceArrayDoc.Fields[7].Note = ""
	InstanceArrayDoc.Fields[7].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum GPU frequency."
	InstanceArrayDoc.Fields[7].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum GPU frequency."
	InstanceArrayDoc.Fields[8].Name = "processorCoreCount"
	InstanceArrayDoc.Fields[8].Type = "int"
	InstanceArrayDoc.Fields[8].Note = ""
	InstanceArrayDoc.Fields[8].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum core count (hyperthreaded)."
	InstanceArrayDoc.Fields[8].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum core count (hyperthreaded)."
	InstanceArrayDoc.Fields[9].Name = "diskCount"
	InstanceArrayDoc.Fields[9].Type = "int"
	InstanceArrayDoc.Fields[9].Note = ""
	InstanceArrayDoc.Fields[9].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum disk count."
	InstanceArrayDoc.Fields[9].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum disk count."
	InstanceArrayDoc.Fields[10].Name = "diskSizeMBytes"
	InstanceArrayDoc.Fields[10].Type = "int"
	InstanceArrayDoc.Fields[10].Note = ""
	InstanceArrayDoc.Fields[10].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum disk size."
	InstanceArrayDoc.Fields[10].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum disk size."
	InstanceArrayDoc.Fields[11].Name = "diskTypes"
	InstanceArrayDoc.Fields[11].Type = "[]string"
	InstanceArrayDoc.Fields[11].Note = ""
	InstanceArrayDoc.Fields[11].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this disk type. This assumes all disks are identical."
	InstanceArrayDoc.Fields[11].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this disk type. This assumes all disks are identical."
	InstanceArrayDoc.Fields[11].Values = []string{
		"ssh",
		"hdd",
	}
	InstanceArrayDoc.Fields[12].Name = "infrastructureID"
	InstanceArrayDoc.Fields[12].Type = "int"
	InstanceArrayDoc.Fields[12].Note = ""
	InstanceArrayDoc.Fields[12].Description = "The id of the infrastructure on which this infrastructure is created on."
	InstanceArrayDoc.Fields[12].Comments[encoder.LineComment] = "The id of the infrastructure on which this infrastructure is created on."
	InstanceArrayDoc.Fields[13].Name = "serviceStatus"
	InstanceArrayDoc.Fields[13].Type = "string"
	InstanceArrayDoc.Fields[13].Note = ""
	InstanceArrayDoc.Fields[13].Description = "The service status.  Read only."
	InstanceArrayDoc.Fields[13].Comments[encoder.LineComment] = "The service status.  Read only."
	InstanceArrayDoc.Fields[13].Values = []string{
		"ordered",
		"active",
		"suspended",
		"stopped",
		"deleted",
	}
	InstanceArrayDoc.Fields[14].Name = "interfaces"
	InstanceArrayDoc.Fields[14].Type = "[]InstanceArrayInterface"
	InstanceArrayDoc.Fields[14].Note = ""
	InstanceArrayDoc.Fields[14].Description = "The instance array interfaces configuration"
	InstanceArrayDoc.Fields[14].Comments[encoder.LineComment] = "The instance array interfaces configuration"
	InstanceArrayDoc.Fields[15].Name = "clusterID"
	InstanceArrayDoc.Fields[15].Type = "int"
	InstanceArrayDoc.Fields[15].Note = ""
	InstanceArrayDoc.Fields[15].Description = "The cluster (such as Kubernetes, VMWare vSphere etc) of which this instance array is part of. A vanilla cluster is created for all instance arrays not added to any application cluster."
	InstanceArrayDoc.Fields[15].Comments[encoder.LineComment] = "The cluster (such as Kubernetes, VMWare vSphere etc) of which this instance array is part of. A vanilla cluster is created for all instance arrays not added to any application cluster."
	InstanceArrayDoc.Fields[16].Name = "clusterRoleGroup"
	InstanceArrayDoc.Fields[16].Type = "string"
	InstanceArrayDoc.Fields[16].Note = ""
	InstanceArrayDoc.Fields[16].Description = "If part of an app cluster this field will receive the role that this instance array has such as `master` or `worker` which is application specific."
	InstanceArrayDoc.Fields[16].Comments[encoder.LineComment] = "If part of an app cluster this field will receive the role that this instance array has such as `master` or `worker` which is application specific."
	InstanceArrayDoc.Fields[17].Name = "firewallManaged"
	InstanceArrayDoc.Fields[17].Type = "bool"
	InstanceArrayDoc.Fields[17].Note = ""
	InstanceArrayDoc.Fields[17].Description = "description: If set to true, the firewall will be configured based on rules provided in the InstanceArrayFirewallRules field. Note that for this to work the following conditions must be fufilled:\na. The OS template should have the template set capability (for the first configuration of the firewall, at install time)\nb. The in-band site controller agent should be enabled with in-band access to the operating system over SSH.\n"
	InstanceArrayDoc.Fields[17].Comments[encoder.LineComment] = "description: If set to true, the firewall will be configured based on rules provided in the InstanceArrayFirewallRules field. Note that for this to work the following conditions must be fufilled:"
	InstanceArrayDoc.Fields[18].Name = "firewallRules"
	InstanceArrayDoc.Fields[18].Type = "[]FirewallRule"
	InstanceArrayDoc.Fields[18].Note = ""
	InstanceArrayDoc.Fields[18].Description = "The list of firewall rules to configure"
	InstanceArrayDoc.Fields[18].Comments[encoder.LineComment] = "The list of firewall rules to configure"
	InstanceArrayDoc.Fields[19].Name = "volumeTemplateID"
	InstanceArrayDoc.Fields[19].Type = "int"
	InstanceArrayDoc.Fields[19].Note = ""
	InstanceArrayDoc.Fields[19].Description = "The operating system template to use."
	InstanceArrayDoc.Fields[19].Comments[encoder.LineComment] = "The operating system template to use."
	InstanceArrayDoc.Fields[20].Name = "operation"
	InstanceArrayDoc.Fields[20].Type = "InstanceArrayOperation"
	InstanceArrayDoc.Fields[20].Note = ""
	InstanceArrayDoc.Fields[20].Description = "Used when changing an instance array. It captures the operation that needs to happen on the instance array."
	InstanceArrayDoc.Fields[20].Comments[encoder.LineComment] = "Used when changing an instance array. It captures the operation that needs to happen on the instance array."
	InstanceArrayDoc.Fields[21].Name = "additionalWanIPv4"
	InstanceArrayDoc.Fields[21].Type = "string"
	InstanceArrayDoc.Fields[21].Note = ""
	InstanceArrayDoc.Fields[21].Description = "Information about additional ips to be assigned to the WAN interfaces. Used internally."
	InstanceArrayDoc.Fields[21].Comments[encoder.LineComment] = "Information about additional ips to be assigned to the WAN interfaces. Used internally."
	InstanceArrayDoc.Fields[22].Name = "customVariables"
	InstanceArrayDoc.Fields[22].Type = "interface{}"
	InstanceArrayDoc.Fields[22].Note = ""
	InstanceArrayDoc.Fields[22].Description = "Custom variables and variable overrides to be pushed to the operating system deployment process."
	InstanceArrayDoc.Fields[22].Comments[encoder.LineComment] = "Custom variables and variable overrides to be pushed to the operating system deployment process."
	InstanceArrayDoc.Fields[23].Name = "firmwarePolicies"
	InstanceArrayDoc.Fields[23].Type = "[]int"
	InstanceArrayDoc.Fields[23].Note = ""
	InstanceArrayDoc.Fields[23].Description = "Firmware policies to apply. Deprecated. Use baselines."
	InstanceArrayDoc.Fields[23].Comments[encoder.LineComment] = "Firmware policies to apply. Deprecated. Use baselines."
	InstanceArrayDoc.Fields[24].Name = "drive_array_id_boot"
	InstanceArrayDoc.Fields[24].Type = "int"
	InstanceArrayDoc.Fields[24].Note = ""
	InstanceArrayDoc.Fields[24].Description = "When iSCSI boot is used this is the id of the drive array that will be the boot device."
	InstanceArrayDoc.Fields[24].Comments[encoder.LineComment] = "When iSCSI boot is used this is the id of the drive array that will be the boot device."

	InstanceArrayOperationDoc.Type = "InstanceArrayOperation"
	InstanceArrayOperationDoc.Comments[encoder.LineComment] = "InstanceArrayOperation object describes the changes that will be applied to an instance array"
	InstanceArrayOperationDoc.Description = "InstanceArrayOperation object describes the changes that will be applied to an instance array"
	InstanceArrayOperationDoc.AppearsIn = []encoder.Appearance{
		{
			TypeName:  "InstanceArray",
			FieldName: "operation",
		},
	}
	InstanceArrayOperationDoc.Fields = make([]encoder.Doc, 26)
	InstanceArrayOperationDoc.Fields[0].Name = "id"
	InstanceArrayOperationDoc.Fields[0].Type = "int"
	InstanceArrayOperationDoc.Fields[0].Note = ""
	InstanceArrayOperationDoc.Fields[0].Description = "The ID of the object."
	InstanceArrayOperationDoc.Fields[0].Comments[encoder.LineComment] = "The ID of the object."
	InstanceArrayOperationDoc.Fields[1].Name = "label"
	InstanceArrayOperationDoc.Fields[1].Type = "string"
	InstanceArrayOperationDoc.Fields[1].Note = ""
	InstanceArrayOperationDoc.Fields[1].Description = "description: The label of the object. Must be unique per infrastructure. Must follow DNS naming rules: Pattern: ^[a-zA-Z]{1,1}[a-zA-Z0-9-]{0,61}[a-zA-Z0-9]{1,1}|[a-zA-Z]{1,1}$"
	InstanceArrayOperationDoc.Fields[1].Comments[encoder.LineComment] = "description: The label of the object. Must be unique per infrastructure. Must follow DNS naming rules: Pattern: ^[a-zA-Z]{1,1}[a-zA-Z0-9-]{0,61}[a-zA-Z0-9]{1,1}|[a-zA-Z]{1,1}$"
	InstanceArrayOperationDoc.Fields[2].Name = "subdomain"
	InstanceArrayOperationDoc.Fields[2].Type = "string"
	InstanceArrayOperationDoc.Fields[2].Note = ""
	InstanceArrayOperationDoc.Fields[2].Description = "description: |\n		User editable DNS record that gets created for this instance array in the built-in DNS\n		service and associated with all the primary IP address on the WAN network. Must adhere to DNS naming rules such\n     as:  only \"-\", lowercase alphanumeric characters and not start with a number.\n     Pattern:\n"
	InstanceArrayOperationDoc.Fields[2].Comments[encoder.LineComment] = "description: |"
	InstanceArrayOperationDoc.Fields[3].Name = "bootMethod"
	InstanceArrayOperationDoc.Fields[3].Type = "string"
	InstanceArrayOperationDoc.Fields[3].Note = ""
	InstanceArrayOperationDoc.Fields[3].Description = "description: The booth method to use. Note that the pxe_iscsi booth method is deprecated.\nvalues:\n	- local_disks\n - pxe_iscsi\n"
	InstanceArrayOperationDoc.Fields[3].Comments[encoder.LineComment] = "description: The booth method to use. Note that the pxe_iscsi booth method is deprecated."
	InstanceArrayOperationDoc.Fields[4].Name = "instanceCount"
	InstanceArrayOperationDoc.Fields[4].Type = "int"
	InstanceArrayOperationDoc.Fields[4].Note = ""
	InstanceArrayOperationDoc.Fields[4].Description = "The number of instances in this array."
	InstanceArrayOperationDoc.Fields[4].Comments[encoder.LineComment] = "The number of instances in this array."
	InstanceArrayOperationDoc.Fields[5].Name = "ramGBytes"
	InstanceArrayOperationDoc.Fields[5].Type = "int"
	InstanceArrayOperationDoc.Fields[5].Note = ""
	InstanceArrayOperationDoc.Fields[5].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum amount of RAM expressed in GB."
	InstanceArrayOperationDoc.Fields[5].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum amount of RAM expressed in GB."
	InstanceArrayOperationDoc.Fields[6].Name = "processorCount"
	InstanceArrayOperationDoc.Fields[6].Type = "int"
	InstanceArrayOperationDoc.Fields[6].Note = ""
	InstanceArrayOperationDoc.Fields[6].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum amount of CPU sockets."
	InstanceArrayOperationDoc.Fields[6].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum amount of CPU sockets."
	InstanceArrayOperationDoc.Fields[7].Name = "processorCoreMhz"
	InstanceArrayOperationDoc.Fields[7].Type = "int"
	InstanceArrayOperationDoc.Fields[7].Note = ""
	InstanceArrayOperationDoc.Fields[7].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum GPU frequency."
	InstanceArrayOperationDoc.Fields[7].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum GPU frequency."
	InstanceArrayOperationDoc.Fields[8].Name = "processorCoreCount"
	InstanceArrayOperationDoc.Fields[8].Type = "int"
	InstanceArrayOperationDoc.Fields[8].Note = ""
	InstanceArrayOperationDoc.Fields[8].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum core count (hyperthreaded)."
	InstanceArrayOperationDoc.Fields[8].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum core count (hyperthreaded)."
	InstanceArrayOperationDoc.Fields[9].Name = "diskCount"
	InstanceArrayOperationDoc.Fields[9].Type = "int"
	InstanceArrayOperationDoc.Fields[9].Note = ""
	InstanceArrayOperationDoc.Fields[9].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum disk count."
	InstanceArrayOperationDoc.Fields[9].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum disk count."
	InstanceArrayOperationDoc.Fields[10].Name = "diskSizeMBytes"
	InstanceArrayOperationDoc.Fields[10].Type = "int"
	InstanceArrayOperationDoc.Fields[10].Note = ""
	InstanceArrayOperationDoc.Fields[10].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum disk size."
	InstanceArrayOperationDoc.Fields[10].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this minimum disk size."
	InstanceArrayOperationDoc.Fields[11].Name = "diskTypes"
	InstanceArrayOperationDoc.Fields[11].Type = "[]string"
	InstanceArrayOperationDoc.Fields[11].Note = ""
	InstanceArrayOperationDoc.Fields[11].Description = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this disk type. This assumes all disks are identical."
	InstanceArrayOperationDoc.Fields[11].Comments[encoder.LineComment] = "When the ServerTypeID is not set on the Instance object this will restrict the search for a matching server to just those with this disk type. This assumes all disks are identical."
	InstanceArrayOperationDoc.Fields[11].Values = []string{
		"ssh",
		"hdd",
	}
	InstanceArrayOperationDoc.Fields[12].Name = "serviceStatus"
	InstanceArrayOperationDoc.Fields[12].Type = "string"
	InstanceArrayOperationDoc.Fields[12].Note = ""
	InstanceArrayOperationDoc.Fields[12].Description = "The service status.  Read only."
	InstanceArrayOperationDoc.Fields[12].Comments[encoder.LineComment] = "The service status.  Read only."
	InstanceArrayOperationDoc.Fields[12].Values = []string{
		"ordered",
		"active",
		"suspended",
		"stopped",
		"deleted",
	}
	InstanceArrayOperationDoc.Fields[13].Name = "interfaces"
	InstanceArrayOperationDoc.Fields[13].Type = "[]InstanceArrayInterfaceOperation"
	InstanceArrayOperationDoc.Fields[13].Note = ""
	InstanceArrayOperationDoc.Fields[13].Description = "The instance array interfaces configuration"
	InstanceArrayOperationDoc.Fields[13].Comments[encoder.LineComment] = "The instance array interfaces configuration"
	InstanceArrayOperationDoc.Fields[14].Name = "clusterID"
	InstanceArrayOperationDoc.Fields[14].Type = "int"
	InstanceArrayOperationDoc.Fields[14].Note = ""
	InstanceArrayOperationDoc.Fields[14].Description = "The cluster (such as Kubernetes, VMWare vSphere etc) of which this instance array is part of. A vanilla cluster is created for all instance arrays not added to any application cluster."
	InstanceArrayOperationDoc.Fields[14].Comments[encoder.LineComment] = "The cluster (such as Kubernetes, VMWare vSphere etc) of which this instance array is part of. A vanilla cluster is created for all instance arrays not added to any application cluster."
	InstanceArrayOperationDoc.Fields[15].Name = "clusterRoleGroup"
	InstanceArrayOperationDoc.Fields[15].Type = "string"
	InstanceArrayOperationDoc.Fields[15].Note = ""
	InstanceArrayOperationDoc.Fields[15].Description = "If part of an app cluster this field will receive the role that this instance array has such as master or worker which is application specific."
	InstanceArrayOperationDoc.Fields[15].Comments[encoder.LineComment] = "If part of an app cluster this field will receive the role that this instance array has such as master or worker which is application specific."
	InstanceArrayOperationDoc.Fields[16].Name = "firewallManaged"
	InstanceArrayOperationDoc.Fields[16].Type = "bool"
	InstanceArrayOperationDoc.Fields[16].Note = ""
	InstanceArrayOperationDoc.Fields[16].Description = "description: If set to true, the firewall will be configured based on rules provided in the InstanceArrayFirewallRules field. Note that for this to work the following conditions must be fufilled:\na. The OS template should have the template set capability (for the first configuration of the firewall, at install time)\nb. The in-band site controller agent should be enabled with in-band access to the operating system over SSH.\n"
	InstanceArrayOperationDoc.Fields[16].Comments[encoder.LineComment] = "description: If set to true, the firewall will be configured based on rules provided in the InstanceArrayFirewallRules field. Note that for this to work the following conditions must be fufilled:"
	InstanceArrayOperationDoc.Fields[17].Name = "firewallRules"
	InstanceArrayOperationDoc.Fields[17].Type = "[]FirewallRule"
	InstanceArrayOperationDoc.Fields[17].Note = ""
	InstanceArrayOperationDoc.Fields[17].Description = "The list of firewall rules to configure"
	InstanceArrayOperationDoc.Fields[17].Comments[encoder.LineComment] = "The list of firewall rules to configure"
	InstanceArrayOperationDoc.Fields[18].Name = "volumeTemplateID"
	InstanceArrayOperationDoc.Fields[18].Type = "int"
	InstanceArrayOperationDoc.Fields[18].Note = ""
	InstanceArrayOperationDoc.Fields[18].Description = "The operating system template to use."
	InstanceArrayOperationDoc.Fields[18].Comments[encoder.LineComment] = "The operating system template to use."
	InstanceArrayOperationDoc.Fields[19].Name = "deployType"
	InstanceArrayOperationDoc.Fields[19].Type = "string"
	InstanceArrayOperationDoc.Fields[19].Note = ""
	InstanceArrayOperationDoc.Fields[19].Description = "description: The deploy type, one of:\nvalues:\n    - create\n	   - delete\n    - edit\n	   - start\n    - stop\n	   - suspend\n"
	InstanceArrayOperationDoc.Fields[19].Comments[encoder.LineComment] = "description: The deploy type, one of:"
	InstanceArrayOperationDoc.Fields[20].Name = "deployStatus"
	InstanceArrayOperationDoc.Fields[20].Type = "string"
	InstanceArrayOperationDoc.Fields[20].Note = ""
	InstanceArrayOperationDoc.Fields[20].Description = "The status of the deployment"
	InstanceArrayOperationDoc.Fields[20].Comments[encoder.LineComment] = "The status of the deployment"
	InstanceArrayOperationDoc.Fields[20].Values = []string{
		"not_started",
		"ongoing",
		"finished",
	}
	InstanceArrayOperationDoc.Fields[21].Name = "changeID"
	InstanceArrayOperationDoc.Fields[21].Type = "int"
	InstanceArrayOperationDoc.Fields[21].Note = ""
	InstanceArrayOperationDoc.Fields[21].Description = "The id of the change operation. Readonly."
	InstanceArrayOperationDoc.Fields[21].Comments[encoder.LineComment] = "The id of the change operation. Readonly."
	InstanceArrayOperationDoc.Fields[22].Name = "additionalWanIPv4"
	InstanceArrayOperationDoc.Fields[22].Type = "string"
	InstanceArrayOperationDoc.Fields[22].Note = ""
	InstanceArrayOperationDoc.Fields[22].Description = "Information about additional ips to be assigned to the WAN interfaces. Used internally."
	InstanceArrayOperationDoc.Fields[22].Comments[encoder.LineComment] = "Information about additional ips to be assigned to the WAN interfaces. Used internally."
	InstanceArrayOperationDoc.Fields[23].Name = "customVariables"
	InstanceArrayOperationDoc.Fields[23].Type = "interface{}"
	InstanceArrayOperationDoc.Fields[23].Note = ""
	InstanceArrayOperationDoc.Fields[23].Description = "Custom variables and variable overrides to be pushed to the operating system deployment process."
	InstanceArrayOperationDoc.Fields[23].Comments[encoder.LineComment] = "Custom variables and variable overrides to be pushed to the operating system deployment process."
	InstanceArrayOperationDoc.Fields[24].Name = "firmwarePolicies"
	InstanceArrayOperationDoc.Fields[24].Type = "[]int"
	InstanceArrayOperationDoc.Fields[24].Note = ""
	InstanceArrayOperationDoc.Fields[24].Description = "Firmware policies to apply. Deprecated. Use baselines instead."
	InstanceArrayOperationDoc.Fields[24].Comments[encoder.LineComment] = "Firmware policies to apply. Deprecated. Use baselines instead."
	InstanceArrayOperationDoc.Fields[25].Name = "drive_array_id_boot"
	InstanceArrayOperationDoc.Fields[25].Type = "int"
	InstanceArrayOperationDoc.Fields[25].Note = ""
	InstanceArrayOperationDoc.Fields[25].Description = "When iSCSI boot is used this is the id of the drive array that will be the boot device."
	InstanceArrayOperationDoc.Fields[25].Comments[encoder.LineComment] = "When iSCSI boot is used this is the id of the drive array that will be the boot device."

	InstanceArrayInterfaceDoc.Type = "InstanceArrayInterface"
	InstanceArrayInterfaceDoc.Comments[encoder.LineComment] = "InstanceArrayInterface describes a network interface of the array."
	InstanceArrayInterfaceDoc.Description = "InstanceArrayInterface describes a network interface of the array.\nIt's properties will be applied to all InstanceInterfaces of the array's instances.\n"
	InstanceArrayInterfaceDoc.AppearsIn = []encoder.Appearance{
		{
			TypeName:  "InstanceArray",
			FieldName: "interfaces",
		},
	}
	InstanceArrayInterfaceDoc.Fields = make([]encoder.Doc, 12)
	InstanceArrayInterfaceDoc.Fields[0].Name = "label"
	InstanceArrayInterfaceDoc.Fields[0].Type = "string"
	InstanceArrayInterfaceDoc.Fields[0].Note = ""
	InstanceArrayInterfaceDoc.Fields[0].Description = "Label of the interface"
	InstanceArrayInterfaceDoc.Fields[0].Comments[encoder.LineComment] = "Label of the interface"
	InstanceArrayInterfaceDoc.Fields[1].Name = "subdomain"
	InstanceArrayInterfaceDoc.Fields[1].Type = "string"
	InstanceArrayInterfaceDoc.Fields[1].Note = ""
	InstanceArrayInterfaceDoc.Fields[1].Description = "An unique string describing the interface."
	InstanceArrayInterfaceDoc.Fields[1].Comments[encoder.LineComment] = "An unique string describing the interface."
	InstanceArrayInterfaceDoc.Fields[2].Name = "id"
	InstanceArrayInterfaceDoc.Fields[2].Type = "int"
	InstanceArrayInterfaceDoc.Fields[2].Note = ""
	InstanceArrayInterfaceDoc.Fields[2].Description = "Interface ID. A unique id of the interface."
	InstanceArrayInterfaceDoc.Fields[2].Comments[encoder.LineComment] = "Interface ID. A unique id of the interface."
	InstanceArrayInterfaceDoc.Fields[3].Name = "instanceArrayID"
	InstanceArrayInterfaceDoc.Fields[3].Type = "int"
	InstanceArrayInterfaceDoc.Fields[3].Note = ""
	InstanceArrayInterfaceDoc.Fields[3].Description = "The instance array to which this interface is associated to"
	InstanceArrayInterfaceDoc.Fields[3].Comments[encoder.LineComment] = "The instance array to which this interface is associated to"
	InstanceArrayInterfaceDoc.Fields[4].Name = "networkID"
	InstanceArrayInterfaceDoc.Fields[4].Type = "int"
	InstanceArrayInterfaceDoc.Fields[4].Note = ""
	InstanceArrayInterfaceDoc.Fields[4].Description = "The ID of the Network to which this interface is connected to. Can be 0 if the interface is not connected."
	InstanceArrayInterfaceDoc.Fields[4].Comments[encoder.LineComment] = "The ID of the Network to which this interface is connected to. Can be 0 if the interface is not connected."
	InstanceArrayInterfaceDoc.Fields[5].Name = "LAGGIndexes"
	InstanceArrayInterfaceDoc.Fields[5].Type = "[]interface{}"
	InstanceArrayInterfaceDoc.Fields[5].Note = ""
	InstanceArrayInterfaceDoc.Fields[5].Description = "Used internally. Readonly."
	InstanceArrayInterfaceDoc.Fields[5].Comments[encoder.LineComment] = "Used internally. Readonly."
	InstanceArrayInterfaceDoc.Fields[6].Name = "index"
	InstanceArrayInterfaceDoc.Fields[6].Type = "int"
	InstanceArrayInterfaceDoc.Fields[6].Note = ""
	InstanceArrayInterfaceDoc.Fields[6].Description = "description: |\n	The index of the interface in the server. This is 0-based and configured based on the lexicographic sorting of the switch and switch ports\n	thus NOT based on the PCI slots or anything like that. This ensures consistent ordering regardless of cabling and/or NIC seating.\n"
	InstanceArrayInterfaceDoc.Fields[6].Comments[encoder.LineComment] = "description: |"
	InstanceArrayInterfaceDoc.Fields[7].Name = "serviceStatus"
	InstanceArrayInterfaceDoc.Fields[7].Type = "string"
	InstanceArrayInterfaceDoc.Fields[7].Note = ""
	InstanceArrayInterfaceDoc.Fields[7].Description = "The service status.  Read only."
	InstanceArrayInterfaceDoc.Fields[7].Comments[encoder.LineComment] = "The service status.  Read only."
	InstanceArrayInterfaceDoc.Fields[7].Values = []string{
		"ordered",
		"active",
		"suspended",
		"stopped",
		"deleted",
	}
	InstanceArrayInterfaceDoc.Fields[8].Name = "createdTimestamp"
	InstanceArrayInterfaceDoc.Fields[8].Type = "string"
	InstanceArrayInterfaceDoc.Fields[8].Note = ""
	InstanceArrayInterfaceDoc.Fields[8].Description = "The creation date and time in ISO 8601 format."
	InstanceArrayInterfaceDoc.Fields[8].Comments[encoder.LineComment] = "The creation date and time in ISO 8601 format."
	InstanceArrayInterfaceDoc.Fields[9].Name = "updatedTimestamp"
	InstanceArrayInterfaceDoc.Fields[9].Type = "string"
	InstanceArrayInterfaceDoc.Fields[9].Note = ""
	InstanceArrayInterfaceDoc.Fields[9].Description = "The last update date and time in ISO 8601 format."
	InstanceArrayInterfaceDoc.Fields[9].Comments[encoder.LineComment] = "The last update date and time in ISO 8601 format."
	InstanceArrayInterfaceDoc.Fields[10].Name = "operation"
	InstanceArrayInterfaceDoc.Fields[10].Type = "InstanceArrayInterfaceOperation"
	InstanceArrayInterfaceDoc.Fields[10].Note = ""
	InstanceArrayInterfaceDoc.Fields[10].Description = "The operation object. Must be set to alter the configuration of an interface."
	InstanceArrayInterfaceDoc.Fields[10].Comments[encoder.LineComment] = "The operation object. Must be set to alter the configuration of an interface."
	InstanceArrayInterfaceDoc.Fields[11].Name = "instance_array_interface_change_id"
	InstanceArrayInterfaceDoc.Fields[11].Type = "int"
	InstanceArrayInterfaceDoc.Fields[11].Note = ""
	InstanceArrayInterfaceDoc.Fields[11].Description = "Ongoing change ID. Readonly."
	InstanceArrayInterfaceDoc.Fields[11].Comments[encoder.LineComment] = "Ongoing change ID. Readonly."

	InstanceArrayInterfaceOperationDoc.Type = "InstanceArrayInterfaceOperation"
	InstanceArrayInterfaceOperationDoc.Comments[encoder.LineComment] = "InstanceArrayInterfaceOperation describes changes to a network array interface"
	InstanceArrayInterfaceOperationDoc.Description = "InstanceArrayInterfaceOperation describes changes to a network array interface"
	InstanceArrayInterfaceOperationDoc.AppearsIn = []encoder.Appearance{
		{
			TypeName:  "InstanceArrayOperation",
			FieldName: "interfaces",
		},
		{
			TypeName:  "InstanceArrayInterface",
			FieldName: "operation",
		},
	}
	InstanceArrayInterfaceOperationDoc.Fields = make([]encoder.Doc, 11)
	InstanceArrayInterfaceOperationDoc.Fields[0].Name = "label"
	InstanceArrayInterfaceOperationDoc.Fields[0].Type = "string"
	InstanceArrayInterfaceOperationDoc.Fields[0].Note = ""
	InstanceArrayInterfaceOperationDoc.Fields[0].Description = "Label of the interface"
	InstanceArrayInterfaceOperationDoc.Fields[0].Comments[encoder.LineComment] = "Label of the interface"
	InstanceArrayInterfaceOperationDoc.Fields[1].Name = "subdomain"
	InstanceArrayInterfaceOperationDoc.Fields[1].Type = "string"
	InstanceArrayInterfaceOperationDoc.Fields[1].Note = ""
	InstanceArrayInterfaceOperationDoc.Fields[1].Description = "An unique string describing the interface."
	InstanceArrayInterfaceOperationDoc.Fields[1].Comments[encoder.LineComment] = "An unique string describing the interface."
	InstanceArrayInterfaceOperationDoc.Fields[2].Name = "id"
	InstanceArrayInterfaceOperationDoc.Fields[2].Type = "int"
	InstanceArrayInterfaceOperationDoc.Fields[2].Note = ""
	InstanceArrayInterfaceOperationDoc.Fields[2].Description = "Interface ID. A unique id of the interface."
	InstanceArrayInterfaceOperationDoc.Fields[2].Comments[encoder.LineComment] = "Interface ID. A unique id of the interface."
	InstanceArrayInterfaceOperationDoc.Fields[3].Name = "instanceArrayID"
	InstanceArrayInterfaceOperationDoc.Fields[3].Type = "int"
	InstanceArrayInterfaceOperationDoc.Fields[3].Note = ""
	InstanceArrayInterfaceOperationDoc.Fields[3].Description = "The instance array to which this interface is associated to"
	InstanceArrayInterfaceOperationDoc.Fields[3].Comments[encoder.LineComment] = "The instance array to which this interface is associated to"
	InstanceArrayInterfaceOperationDoc.Fields[4].Name = "networkID"
	InstanceArrayInterfaceOperationDoc.Fields[4].Type = "int"
	InstanceArrayInterfaceOperationDoc.Fields[4].Note = ""
	InstanceArrayInterfaceOperationDoc.Fields[4].Description = "The ID of the Network to which this interface is connected to. Can be 0 if the interface is not connected."
	InstanceArrayInterfaceOperationDoc.Fields[4].Comments[encoder.LineComment] = "The ID of the Network to which this interface is connected to. Can be 0 if the interface is not connected."
	InstanceArrayInterfaceOperationDoc.Fields[5].Name = "LAGGIndexes"
	InstanceArrayInterfaceOperationDoc.Fields[5].Type = "[]interface{}"
	InstanceArrayInterfaceOperationDoc.Fields[5].Note = ""
	InstanceArrayInterfaceOperationDoc.Fields[5].Description = "Used internally. Readonly."
	InstanceArrayInterfaceOperationDoc.Fields[5].Comments[encoder.LineComment] = "Used internally. Readonly."
	InstanceArrayInterfaceOperationDoc.Fields[6].Name = "index"
	InstanceArrayInterfaceOperationDoc.Fields[6].Type = "int"
	InstanceArrayInterfaceOperationDoc.Fields[6].Note = ""
	InstanceArrayInterfaceOperationDoc.Fields[6].Description = "description: |\n	The index of the interface in the server. This is 0-based and configured based on the lexicographic sorting of the switch and switch ports\n	thus NOT based on the PCI slots or anything like that. This ensures consistent ordering regardless of cabling and/or NIC seating.\n"
	InstanceArrayInterfaceOperationDoc.Fields[6].Comments[encoder.LineComment] = "description: |"
	InstanceArrayInterfaceOperationDoc.Fields[7].Name = "serviceStatus"
	InstanceArrayInterfaceOperationDoc.Fields[7].Type = "string"
	InstanceArrayInterfaceOperationDoc.Fields[7].Note = ""
	InstanceArrayInterfaceOperationDoc.Fields[7].Description = "The service status.  Read only."
	InstanceArrayInterfaceOperationDoc.Fields[7].Comments[encoder.LineComment] = "The service status.  Read only."
	InstanceArrayInterfaceOperationDoc.Fields[7].Values = []string{
		"ordered",
		"active",
		"suspended",
		"stopped",
		"deleted",
	}
	InstanceArrayInterfaceOperationDoc.Fields[8].Name = "createdTimestamp"
	InstanceArrayInterfaceOperationDoc.Fields[8].Type = "string"
	InstanceArrayInterfaceOperationDoc.Fields[8].Note = ""
	InstanceArrayInterfaceOperationDoc.Fields[8].Description = "The creation date and time in ISO 8601 format."
	InstanceArrayInterfaceOperationDoc.Fields[8].Comments[encoder.LineComment] = "The creation date and time in ISO 8601 format."
	InstanceArrayInterfaceOperationDoc.Fields[9].Name = "updatedTimestamp"
	InstanceArrayInterfaceOperationDoc.Fields[9].Type = "string"
	InstanceArrayInterfaceOperationDoc.Fields[9].Note = ""
	InstanceArrayInterfaceOperationDoc.Fields[9].Description = "The last update date and time in ISO 8601 format."
	InstanceArrayInterfaceOperationDoc.Fields[9].Comments[encoder.LineComment] = "The last update date and time in ISO 8601 format."
	InstanceArrayInterfaceOperationDoc.Fields[10].Name = "changeID"
	InstanceArrayInterfaceOperationDoc.Fields[10].Type = "int"
	InstanceArrayInterfaceOperationDoc.Fields[10].Note = ""
	InstanceArrayInterfaceOperationDoc.Fields[10].Description = "Ongoing change ID. Readonly."
	InstanceArrayInterfaceOperationDoc.Fields[10].Comments[encoder.LineComment] = "Ongoing change ID. Readonly."
}

func (InstanceArray) Doc() *encoder.Doc {
	return &InstanceArrayDoc
}

func (InstanceArrayOperation) Doc() *encoder.Doc {
	return &InstanceArrayOperationDoc
}

func (InstanceArrayInterface) Doc() *encoder.Doc {
	return &InstanceArrayInterfaceDoc
}

func (InstanceArrayInterfaceOperation) Doc() *encoder.Doc {
	return &InstanceArrayInterfaceOperationDoc
}

// GetInstanceArrayDoc returns documentation for the file ./.
func GetInstanceArrayDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "InstanceArray",
		Description: "",
		Structs: []*encoder.Doc{
			&InstanceArrayDoc,
			&InstanceArrayOperationDoc,
			&InstanceArrayInterfaceDoc,
			&InstanceArrayInterfaceOperationDoc,
		},
	}
}
