// DO NOT EDIT: this file is automatically generated by docgen
package metalcloud

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var (
	NetworkDoc          encoder.Doc
	NetworkOperationDoc encoder.Doc
)

func init() {
	NetworkDoc.Type = "Network"
	NetworkDoc.Comments[encoder.LineComment] = "Network object describes an high level connection construct"
	NetworkDoc.Description = "Network object describes an high level connection construct"
	NetworkDoc.Fields = make([]encoder.Doc, 9)
	NetworkDoc.Fields[0].Name = "id"
	NetworkDoc.Fields[0].Type = "int"
	NetworkDoc.Fields[0].Note = ""
	NetworkDoc.Fields[0].Description = "The ID of the object."
	NetworkDoc.Fields[0].Comments[encoder.LineComment] = "The ID of the object."
	NetworkDoc.Fields[1].Name = "label"
	NetworkDoc.Fields[1].Type = "string"
	NetworkDoc.Fields[1].Note = ""
	NetworkDoc.Fields[1].Description = "The Label of the object."
	NetworkDoc.Fields[1].Comments[encoder.LineComment] = "The Label of the object."
	NetworkDoc.Fields[2].Name = "subdomain"
	NetworkDoc.Fields[2].Type = "string"
	NetworkDoc.Fields[2].Note = ""
	NetworkDoc.Fields[2].Description = "A unique string representing the network. Deprecated"
	NetworkDoc.Fields[2].Comments[encoder.LineComment] = "A unique string representing the network. Deprecated"
	NetworkDoc.Fields[3].Name = "type"
	NetworkDoc.Fields[3].Type = "string"
	NetworkDoc.Fields[3].Note = ""
	NetworkDoc.Fields[3].Description = "The network type"
	NetworkDoc.Fields[3].Comments[encoder.LineComment] = "The network type"
	NetworkDoc.Fields[3].Values = []string{
		"wan",
		"lan",
		"san",
	}
	NetworkDoc.Fields[4].Name = "infrastructureID"
	NetworkDoc.Fields[4].Type = "int"
	NetworkDoc.Fields[4].Note = ""
	NetworkDoc.Fields[4].Description = "The infrastructure on which this network is defined"
	NetworkDoc.Fields[4].Comments[encoder.LineComment] = "The infrastructure on which this network is defined"
	NetworkDoc.Fields[5].Name = "createdTimestamp"
	NetworkDoc.Fields[5].Type = "string"
	NetworkDoc.Fields[5].Note = ""
	NetworkDoc.Fields[5].Description = "ISO 8601 timestamp which holds the date and time when the network was created."
	NetworkDoc.Fields[5].Comments[encoder.LineComment] = "ISO 8601 timestamp which holds the date and time when the network was created."
	NetworkDoc.Fields[6].Name = "updatedTimestamp"
	NetworkDoc.Fields[6].Type = "string"
	NetworkDoc.Fields[6].Note = ""
	NetworkDoc.Fields[6].Description = "ISO 8601 timestamp which holds the date and time when the network was last updated."
	NetworkDoc.Fields[6].Comments[encoder.LineComment] = "ISO 8601 timestamp which holds the date and time when the network was last updated."
	NetworkDoc.Fields[7].Name = "LANAutoAllocateIPs"
	NetworkDoc.Fields[7].Type = "bool"
	NetworkDoc.Fields[7].Note = ""
	NetworkDoc.Fields[7].Description = "If set to true and if the network is of type LAN IPs will be automatically allocated from any attached subnet pool. Deprecated."
	NetworkDoc.Fields[7].Comments[encoder.LineComment] = "If set to true and if the network is of type LAN IPs will be automatically allocated from any attached subnet pool. Deprecated."
	NetworkDoc.Fields[8].Name = "operation"
	NetworkDoc.Fields[8].Type = "NetworkOperation"
	NetworkDoc.Fields[8].Note = ""
	NetworkDoc.Fields[8].Description = "The operation object."
	NetworkDoc.Fields[8].Comments[encoder.LineComment] = "The operation object."

	NetworkOperationDoc.Type = "NetworkOperation"
	NetworkOperationDoc.Comments[encoder.LineComment] = "NetworkOperation object describes the change(s) required to be applied to a Network"
	NetworkOperationDoc.Description = "NetworkOperation object describes the change(s) required to be applied to a Network"
	NetworkOperationDoc.AppearsIn = []encoder.Appearance{
		{
			TypeName:  "Network",
			FieldName: "operation",
		},
	}
	NetworkOperationDoc.Fields = make([]encoder.Doc, 8)
	NetworkOperationDoc.Fields[0].Name = "id"
	NetworkOperationDoc.Fields[0].Type = "int"
	NetworkOperationDoc.Fields[0].Note = ""
	NetworkOperationDoc.Fields[0].Description = "The ID of the object."
	NetworkOperationDoc.Fields[0].Comments[encoder.LineComment] = "The ID of the object."
	NetworkOperationDoc.Fields[1].Name = "label"
	NetworkOperationDoc.Fields[1].Type = "string"
	NetworkOperationDoc.Fields[1].Note = ""
	NetworkOperationDoc.Fields[1].Description = "The Label of the object."
	NetworkOperationDoc.Fields[1].Comments[encoder.LineComment] = "The Label of the object."
	NetworkOperationDoc.Fields[2].Name = "subdomain"
	NetworkOperationDoc.Fields[2].Type = "string"
	NetworkOperationDoc.Fields[2].Note = ""
	NetworkOperationDoc.Fields[2].Description = "A unique string representing the network. Deprecated"
	NetworkOperationDoc.Fields[2].Comments[encoder.LineComment] = "A unique string representing the network. Deprecated"
	NetworkOperationDoc.Fields[3].Name = "type"
	NetworkOperationDoc.Fields[3].Type = "string"
	NetworkOperationDoc.Fields[3].Note = ""
	NetworkOperationDoc.Fields[3].Description = "The network type"
	NetworkOperationDoc.Fields[3].Comments[encoder.LineComment] = "The network type"
	NetworkOperationDoc.Fields[3].Values = []string{
		"wan",
		"lan",
		"san",
	}
	NetworkOperationDoc.Fields[4].Name = "infrastructureID"
	NetworkOperationDoc.Fields[4].Type = "int"
	NetworkOperationDoc.Fields[4].Note = ""
	NetworkOperationDoc.Fields[4].Description = "The infrastructure on which this network is defined"
	NetworkOperationDoc.Fields[4].Comments[encoder.LineComment] = "The infrastructure on which this network is defined"
	NetworkOperationDoc.Fields[5].Name = "LANAutoAllocateIPs"
	NetworkOperationDoc.Fields[5].Type = "bool"
	NetworkOperationDoc.Fields[5].Note = ""
	NetworkOperationDoc.Fields[5].Description = "If set to true and if the network is of type LAN IPs will be automatically allocated from any attached subnet pool. Deprecated."
	NetworkOperationDoc.Fields[5].Comments[encoder.LineComment] = "If set to true and if the network is of type LAN IPs will be automatically allocated from any attached subnet pool. Deprecated."
	NetworkOperationDoc.Fields[6].Name = "deployType"
	NetworkOperationDoc.Fields[6].Type = "string"
	NetworkOperationDoc.Fields[6].Note = ""
	NetworkOperationDoc.Fields[6].Description = "description: The deploy type\nvalues:\n    - create\n	   - delete\n    - edit\n	   - start\n    - stop\n	   - suspend\n"
	NetworkOperationDoc.Fields[6].Comments[encoder.LineComment] = "description: The deploy type"
	NetworkOperationDoc.Fields[7].Name = "changeID"
	NetworkOperationDoc.Fields[7].Type = "int"
	NetworkOperationDoc.Fields[7].Note = ""
	NetworkOperationDoc.Fields[7].Description = "The id of the change operation. Readonly."
	NetworkOperationDoc.Fields[7].Comments[encoder.LineComment] = "The id of the change operation. Readonly."
}

func (Network) Doc() *encoder.Doc {
	return &NetworkDoc
}

func (NetworkOperation) Doc() *encoder.Doc {
	return &NetworkOperationDoc
}

// GetNetworkDoc returns documentation for the file ./.
func GetNetworkDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "Network",
		Description: "",
		Structs: []*encoder.Doc{
			&NetworkDoc,
			&NetworkOperationDoc,
		},
	}
}
