// DO NOT EDIT: this file is automatically generated by docgen
package metalcloud

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var (
	OSTemplateDoc            encoder.Doc
	OSTemplateCredentialsDoc encoder.Doc
)

func init() {
	OSTemplateDoc.Type = "OSTemplate"
	OSTemplateDoc.Comments[encoder.LineComment] = "OSTemplate A template can be created based on a drive and it has the same characteristics and holds the same information as the parent drive."
	OSTemplateDoc.Description = "OSTemplate A template can be created based on a drive and it has the same characteristics and holds the same information as the parent drive."
	OSTemplateDoc.Fields = make([]encoder.Doc, 27)
	OSTemplateDoc.Fields[0].Name = "id"
	OSTemplateDoc.Fields[0].Type = "int"
	OSTemplateDoc.Fields[0].Note = ""
	OSTemplateDoc.Fields[0].Description = "The id of the object"
	OSTemplateDoc.Fields[0].Comments[encoder.LineComment] = "The id of the object"
	OSTemplateDoc.Fields[1].Name = "label"
	OSTemplateDoc.Fields[1].Type = "string"
	OSTemplateDoc.Fields[1].Note = ""
	OSTemplateDoc.Fields[1].Description = "The label of the object"
	OSTemplateDoc.Fields[1].Comments[encoder.LineComment] = "The label of the object"
	OSTemplateDoc.Fields[2].Name = "name"
	OSTemplateDoc.Fields[2].Type = "string"
	OSTemplateDoc.Fields[2].Note = ""
	OSTemplateDoc.Fields[2].Description = "The display name of the object"
	OSTemplateDoc.Fields[2].Comments[encoder.LineComment] = "The display name of the object"
	OSTemplateDoc.Fields[3].Name = "sizeMBytes"
	OSTemplateDoc.Fields[3].Type = "int"
	OSTemplateDoc.Fields[3].Note = ""
	OSTemplateDoc.Fields[3].Description = "If this is an image type os template, the size of the image"
	OSTemplateDoc.Fields[3].Comments[encoder.LineComment] = "If this is an image type os template, the size of the image"
	OSTemplateDoc.Fields[4].Name = "localDisk"
	OSTemplateDoc.Fields[4].Type = "bool"
	OSTemplateDoc.Fields[4].Note = ""
	OSTemplateDoc.Fields[4].Description = "If set to true if this template can be installed to local disks"
	OSTemplateDoc.Fields[4].Comments[encoder.LineComment] = "If set to true if this template can be installed to local disks"
	OSTemplateDoc.Fields[5].Name = "isOsTemplate"
	OSTemplateDoc.Fields[5].Type = "bool"
	OSTemplateDoc.Fields[5].Note = ""
	OSTemplateDoc.Fields[5].Description = "If set to true this is an unattended install type template. If set to false this will be an image type template."
	OSTemplateDoc.Fields[5].Comments[encoder.LineComment] = "If set to true this is an unattended install type template. If set to false this will be an image type template."
	OSTemplateDoc.Fields[6].Name = ""
	OSTemplateDoc.Fields[6].Type = "bool"
	OSTemplateDoc.Fields[6].Note = ""
	OSTemplateDoc.Fields[6].Description = "If set to true this is a template for switches rather than servers."
	OSTemplateDoc.Fields[6].Comments[encoder.LineComment] = "If set to true this is a template for switches rather than servers."
	OSTemplateDoc.Fields[7].Name = "isImageBuildRequired"
	OSTemplateDoc.Fields[7].Type = "bool"
	OSTemplateDoc.Fields[7].Note = ""
	OSTemplateDoc.Fields[7].Description = "If set to true this is a template that requires a build using the image builder to package assets into the ISO"
	OSTemplateDoc.Fields[7].Comments[encoder.LineComment] = "If set to true this is a template that requires a build using the image builder to package assets into the ISO"
	OSTemplateDoc.Fields[8].Name = "provisionViaOOB"
	OSTemplateDoc.Fields[8].Type = "bool"
	OSTemplateDoc.Fields[8].Note = ""
	OSTemplateDoc.Fields[8].Description = "If set to true this template can be installed via the OOB network (Virtual Media)"
	OSTemplateDoc.Fields[8].Comments[encoder.LineComment] = "If set to true this template can be installed via the OOB network (Virtual Media)"
	OSTemplateDoc.Fields[9].Name = "bootMethods"
	OSTemplateDoc.Fields[9].Type = "string"
	OSTemplateDoc.Fields[9].Note = ""
	OSTemplateDoc.Fields[9].Description = "If set to true this template can be installed via the OOB network (Virtual Media)"
	OSTemplateDoc.Fields[9].Comments[encoder.LineComment] = "If set to true this template can be installed via the OOB network (Virtual Media)"
	OSTemplateDoc.Fields[9].Values = []string{
		"pxe_iscsi",
		"local_drives",
	}
	OSTemplateDoc.Fields[10].Name = ""
	OSTemplateDoc.Fields[10].Type = "string"
	OSTemplateDoc.Fields[10].Note = ""
	OSTemplateDoc.Fields[10].Description = "description: Defines how the template is initialized.\nvalues:\n - \"provisioner_os_bootstrap_dummy\",\n - \"provisioner_os_bootstrap_generic\",\n - \"provisioner_os_bootstrap_centos\",\n - \"provisioner_os_bootstrap_ubuntu\",\n - \"provisioner_os_cloudinit_prepare_centos\",\n - \"provisioner_os_cloudinit_prepare_rhel\",\n - \"provisioner_os_cloudinit_prepare_ubuntu\",\n - \"provisioner_os_cloudbaseinit_prepare_windows\",\n - \"provisioner_os_cloudinit_prepare_generic_unix\",\n - \"provisioner_os_bootstrap_generic_non_cloudinit\n"
	OSTemplateDoc.Fields[10].Comments[encoder.LineComment] = "description: Defines how the template is initialized."
	OSTemplateDoc.Fields[11].Name = "bootType"
	OSTemplateDoc.Fields[11].Type = "string"
	OSTemplateDoc.Fields[11].Note = ""
	OSTemplateDoc.Fields[11].Description = "Controls the type of boot method supported by this template"
	OSTemplateDoc.Fields[11].Comments[encoder.LineComment] = "Controls the type of boot method supported by this template"
	OSTemplateDoc.Fields[11].Values = []string{
		"legacy_only",
		"uefi_only",
		"hybrid",
	}
	OSTemplateDoc.Fields[12].Name = "description"
	OSTemplateDoc.Fields[12].Type = "string"
	OSTemplateDoc.Fields[12].Note = ""
	OSTemplateDoc.Fields[12].Description = "A description of the template"
	OSTemplateDoc.Fields[12].Comments[encoder.LineComment] = "A description of the template"
	OSTemplateDoc.Fields[13].Name = "createdTimestamp"
	OSTemplateDoc.Fields[13].Type = "string"
	OSTemplateDoc.Fields[13].Note = ""
	OSTemplateDoc.Fields[13].Description = "ISO 8601 timestamp which holds the date and time when the template was created. Readonly."
	OSTemplateDoc.Fields[13].Comments[encoder.LineComment] = "ISO 8601 timestamp which holds the date and time when the template was created. Readonly."
	OSTemplateDoc.Fields[14].Name = "updatedTimestamp"
	OSTemplateDoc.Fields[14].Type = "string"
	OSTemplateDoc.Fields[14].Note = ""
	OSTemplateDoc.Fields[14].Description = "ISO 8601 timestamp which holds the date and time when the template was updated. Readonly."
	OSTemplateDoc.Fields[14].Comments[encoder.LineComment] = "ISO 8601 timestamp which holds the date and time when the template was updated. Readonly."
	OSTemplateDoc.Fields[15].Name = "userID"
	OSTemplateDoc.Fields[15].Type = "int"
	OSTemplateDoc.Fields[15].Note = ""
	OSTemplateDoc.Fields[15].Description = "The user that owns this template"
	OSTemplateDoc.Fields[15].Comments[encoder.LineComment] = "The user that owns this template"
	OSTemplateDoc.Fields[16].Name = "os"
	OSTemplateDoc.Fields[16].Type = "OperatingSystem"
	OSTemplateDoc.Fields[16].Note = ""
	OSTemplateDoc.Fields[16].Description = "The operating system details"
	OSTemplateDoc.Fields[16].Comments[encoder.LineComment] = "The operating system details"
	OSTemplateDoc.Fields[17].Name = "repoURL"
	OSTemplateDoc.Fields[17].Type = "string"
	OSTemplateDoc.Fields[17].Note = ""
	OSTemplateDoc.Fields[17].Description = "In some cases additional files are required and these are typically pulled from this URL"
	OSTemplateDoc.Fields[17].Comments[encoder.LineComment] = "In some cases additional files are required and these are typically pulled from this URL"
	OSTemplateDoc.Fields[18].Name = "deprecationStatus"
	OSTemplateDoc.Fields[18].Type = "string"
	OSTemplateDoc.Fields[18].Note = ""
	OSTemplateDoc.Fields[18].Description = "Controls if this template can be used for new provisioning operations or just expanding of existing clusters"
	OSTemplateDoc.Fields[18].Comments[encoder.LineComment] = "Controls if this template can be used for new provisioning operations or just expanding of existing clusters"
	OSTemplateDoc.Fields[18].Values = []string{
		"not_deprecated",
		"deprecated_allow_expand",
		"deprecated_deny_provision",
	}
	OSTemplateDoc.Fields[19].Name = "credentials"
	OSTemplateDoc.Fields[19].Type = "OSTemplateCredentials"
	OSTemplateDoc.Fields[19].Note = ""
	OSTemplateDoc.Fields[19].Description = "Credentials of the template"
	OSTemplateDoc.Fields[19].Comments[encoder.LineComment] = "Credentials of the template"
	OSTemplateDoc.Fields[20].Name = "tags"
	OSTemplateDoc.Fields[20].Type = "[]string"
	OSTemplateDoc.Fields[20].Note = ""
	OSTemplateDoc.Fields[20].Description = "Tags"
	OSTemplateDoc.Fields[20].Comments[encoder.LineComment] = "Tags"
	OSTemplateDoc.Fields[21].Name = "OSAssetIDBootloaderLocalInstall"
	OSTemplateDoc.Fields[21].Type = "int"
	OSTemplateDoc.Fields[21].Note = ""
	OSTemplateDoc.Fields[21].Description = "The ID of the bootloader asset to use during local install"
	OSTemplateDoc.Fields[21].Comments[encoder.LineComment] = "The ID of the bootloader asset to use during local install"
	OSTemplateDoc.Fields[22].Name = "OSAssetIDBootloaderOSBoot"
	OSTemplateDoc.Fields[22].Type = "int"
	OSTemplateDoc.Fields[22].Note = ""
	OSTemplateDoc.Fields[22].Description = "The ID of the bootloader asset to use during initial boot (such as iPXE)"
	OSTemplateDoc.Fields[22].Comments[encoder.LineComment] = "The ID of the bootloader asset to use during initial boot (such as iPXE)"
	OSTemplateDoc.Fields[23].Name = "variablesJSON"
	OSTemplateDoc.Fields[23].Type = "string"
	OSTemplateDoc.Fields[23].Note = ""
	OSTemplateDoc.Fields[23].Description = "Variables this template requires."
	OSTemplateDoc.Fields[23].Comments[encoder.LineComment] = "Variables this template requires."
	OSTemplateDoc.Fields[24].Name = "networkOS"
	OSTemplateDoc.Fields[24].Type = "NetworkOperatingSystem"
	OSTemplateDoc.Fields[24].Note = ""
	OSTemplateDoc.Fields[24].Description = "If this is an network operating system, here are the details"
	OSTemplateDoc.Fields[24].Comments[encoder.LineComment] = "If this is an network operating system, here are the details"
	OSTemplateDoc.Fields[25].Name = ""
	OSTemplateDoc.Fields[25].Type = "string"
	OSTemplateDoc.Fields[25].Note = ""
	OSTemplateDoc.Fields[25].Description = "Version of the operating system"
	OSTemplateDoc.Fields[25].Comments[encoder.LineComment] = "Version of the operating system"
	OSTemplateDoc.Fields[26].Name = ""
	OSTemplateDoc.Fields[26].Type = "string"
	OSTemplateDoc.Fields[26].Note = ""
	OSTemplateDoc.Fields[26].Description = "The method to determine if the OS is ready to use."
	OSTemplateDoc.Fields[26].Comments[encoder.LineComment] = "The method to determine if the OS is ready to use."
	OSTemplateDoc.Fields[26].Values = []string{
		"wait_for_ssh",
		"wait_for_signal_from_os",
		"wait_for_power_off",
		"wait_for_signal_from_os_and_wait_for_power_off",
	}

	OSTemplateCredentialsDoc.Type = "OSTemplateCredentials"
	OSTemplateCredentialsDoc.Comments[encoder.LineComment] = "OSTemplateCredentials holds information needed to connect to an OS installed by an OSTemplate."
	OSTemplateCredentialsDoc.Description = "OSTemplateCredentials holds information needed to connect to an OS installed by an OSTemplate."
	OSTemplateCredentialsDoc.AppearsIn = []encoder.Appearance{
		{
			TypeName:  "OSTemplate",
			FieldName: "credentials",
		},
	}
	OSTemplateCredentialsDoc.Fields = make([]encoder.Doc, 6)
	OSTemplateCredentialsDoc.Fields[0].Name = "initialUser"
	OSTemplateCredentialsDoc.Fields[0].Type = "string"
	OSTemplateCredentialsDoc.Fields[0].Note = ""
	OSTemplateCredentialsDoc.Fields[0].Description = "The initial user"
	OSTemplateCredentialsDoc.Fields[0].Comments[encoder.LineComment] = "The initial user"
	OSTemplateCredentialsDoc.Fields[1].Name = "initialPasswordEncrypted"
	OSTemplateCredentialsDoc.Fields[1].Type = "string"
	OSTemplateCredentialsDoc.Fields[1].Note = ""
	OSTemplateCredentialsDoc.Fields[1].Description = "The initial password. Readonly"
	OSTemplateCredentialsDoc.Fields[1].Comments[encoder.LineComment] = "The initial password. Readonly"
	OSTemplateCredentialsDoc.Fields[2].Name = "initialPassword"
	OSTemplateCredentialsDoc.Fields[2].Type = "string"
	OSTemplateCredentialsDoc.Fields[2].Note = ""
	OSTemplateCredentialsDoc.Fields[2].Description = "The initial password. Write-only"
	OSTemplateCredentialsDoc.Fields[2].Comments[encoder.LineComment] = "The initial password. Write-only"
	OSTemplateCredentialsDoc.Fields[3].Name = "initialSSHPort"
	OSTemplateCredentialsDoc.Fields[3].Type = "int"
	OSTemplateCredentialsDoc.Fields[3].Note = ""
	OSTemplateCredentialsDoc.Fields[3].Description = "The port to use for SSH"
	OSTemplateCredentialsDoc.Fields[3].Comments[encoder.LineComment] = "The port to use for SSH"
	OSTemplateCredentialsDoc.Fields[4].Name = "changePasswordAfterDeploy"
	OSTemplateCredentialsDoc.Fields[4].Type = "bool"
	OSTemplateCredentialsDoc.Fields[4].Note = ""
	OSTemplateCredentialsDoc.Fields[4].Description = "If set, and if the template supports it the password will be changed after deploy (this password will be used only during deploy)."
	OSTemplateCredentialsDoc.Fields[4].Comments[encoder.LineComment] = "If set, and if the template supports it the password will be changed after deploy (this password will be used only during deploy)."
	OSTemplateCredentialsDoc.Fields[5].Name = "useAutogeneratedInitialPassword"
	OSTemplateCredentialsDoc.Fields[5].Type = "bool"
	OSTemplateCredentialsDoc.Fields[5].Note = ""
	OSTemplateCredentialsDoc.Fields[5].Description = "If set, the password will be automatically generated"
	OSTemplateCredentialsDoc.Fields[5].Comments[encoder.LineComment] = "If set, the password will be automatically generated"
}

func (OSTemplate) Doc() *encoder.Doc {
	return &OSTemplateDoc
}

func (OSTemplateCredentials) Doc() *encoder.Doc {
	return &OSTemplateCredentialsDoc
}

// GetOSTemplateDoc returns documentation for the file ./.
func GetOSTemplateDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "OSTemplate",
		Description: "",
		Structs: []*encoder.Doc{
			&OSTemplateDoc,
			&OSTemplateCredentialsDoc,
		},
	}
}
