// DO NOT EDIT: this file is automatically generated by docgen
package metalcloud

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var SecretDoc encoder.Doc

func init() {
	SecretDoc.Type = "Secret"
	SecretDoc.Comments[encoder.LineComment] = "Secret struct defines a server type"
	SecretDoc.Description = "Secret struct defines a server type"
	SecretDoc.Fields = make([]encoder.Doc, 8)
	SecretDoc.Fields[0].Name = "id"
	SecretDoc.Fields[0].Type = "int"
	SecretDoc.Fields[0].Note = ""
	SecretDoc.Fields[0].Description = "The id of the object"
	SecretDoc.Fields[0].Comments[encoder.LineComment] = "The id of the object"
	SecretDoc.Fields[1].Name = "ownerID"
	SecretDoc.Fields[1].Type = "int"
	SecretDoc.Fields[1].Note = ""
	SecretDoc.Fields[1].Description = "The id of the owner of the object"
	SecretDoc.Fields[1].Comments[encoder.LineComment] = "The id of the owner of the object"
	SecretDoc.Fields[2].Name = "userIDAuthenticated"
	SecretDoc.Fields[2].Type = "int"
	SecretDoc.Fields[2].Note = ""
	SecretDoc.Fields[2].Description = "The id of the user that created the object"
	SecretDoc.Fields[2].Comments[encoder.LineComment] = "The id of the user that created the object"
	SecretDoc.Fields[3].Name = "name"
	SecretDoc.Fields[3].Type = "string"
	SecretDoc.Fields[3].Note = ""
	SecretDoc.Fields[3].Description = "The name (label) of the secret"
	SecretDoc.Fields[3].Comments[encoder.LineComment] = "The name (label) of the secret"
	SecretDoc.Fields[4].Name = "usage"
	SecretDoc.Fields[4].Type = "string"
	SecretDoc.Fields[4].Note = ""
	SecretDoc.Fields[4].Description = "How this secret is to be used"
	SecretDoc.Fields[4].Comments[encoder.LineComment] = "How this secret is to be used"
	SecretDoc.Fields[5].Name = "base64"
	SecretDoc.Fields[5].Type = "string"
	SecretDoc.Fields[5].Note = ""
	SecretDoc.Fields[5].Description = "The content of the secret. Readonly."
	SecretDoc.Fields[5].Comments[encoder.LineComment] = "The content of the secret. Readonly."
	SecretDoc.Fields[6].Name = "createdTimestamp"
	SecretDoc.Fields[6].Type = "string"
	SecretDoc.Fields[6].Note = ""
	SecretDoc.Fields[6].Description = "ISO 8601 timestamp which holds the date and time when the secret was created. Readonly."
	SecretDoc.Fields[6].Comments[encoder.LineComment] = "ISO 8601 timestamp which holds the date and time when the secret was created. Readonly."
	SecretDoc.Fields[7].Name = "updatedTimestamp"
	SecretDoc.Fields[7].Type = "string"
	SecretDoc.Fields[7].Note = ""
	SecretDoc.Fields[7].Description = "ISO 8601 timestamp which holds the date and time when the secret was updated. Readonly."
	SecretDoc.Fields[7].Comments[encoder.LineComment] = "ISO 8601 timestamp which holds the date and time when the secret was updated. Readonly."
}

func (Secret) Doc() *encoder.Doc {
	return &SecretDoc
}

// GetSecretDoc returns documentation for the file ./.
func GetSecretDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "Secret",
		Description: "",
		Structs: []*encoder.Doc{
			&SecretDoc,
		},
	}
}
