// DO NOT EDIT: this file is automatically generated by docgen
package metalcloud

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var (
	SubnetPoolDoc            encoder.Doc
	SubnetPoolUtilizationDoc encoder.Doc
)

func init() {
	SubnetPoolDoc.Type = "SubnetPool"
	SubnetPoolDoc.Comments[encoder.LineComment] = "SubnetPool represents a pool of subnets"
	SubnetPoolDoc.Description = "SubnetPool represents a pool of subnets"
	SubnetPoolDoc.Fields = make([]encoder.Doc, 16)
	SubnetPoolDoc.Fields[0].Name = "id"
	SubnetPoolDoc.Fields[0].Type = "int"
	SubnetPoolDoc.Fields[0].Note = ""
	SubnetPoolDoc.Fields[0].Description = "Id of the subnetpool"
	SubnetPoolDoc.Fields[0].Comments[encoder.LineComment] = "Id of the subnetpool"
	SubnetPoolDoc.Fields[1].Name = "datacenter"
	SubnetPoolDoc.Fields[1].Type = "string"
	SubnetPoolDoc.Fields[1].Note = ""
	SubnetPoolDoc.Fields[1].Description = "Label fo the Datacenter"
	SubnetPoolDoc.Fields[1].Comments[encoder.LineComment] = "Label fo the Datacenter"
	SubnetPoolDoc.Fields[2].Name = "networkEquipmentID"
	SubnetPoolDoc.Fields[2].Type = "int"
	SubnetPoolDoc.Fields[2].Note = ""
	SubnetPoolDoc.Fields[2].Description = "ID fo the network equipment to which this subnet pool is associated"
	SubnetPoolDoc.Fields[2].Comments[encoder.LineComment] = "ID fo the network equipment to which this subnet pool is associated"
	SubnetPoolDoc.Fields[3].Name = "user"
	SubnetPoolDoc.Fields[3].Type = "int"
	SubnetPoolDoc.Fields[3].Note = ""
	SubnetPoolDoc.Fields[3].Description = "Owner of this subent pool"
	SubnetPoolDoc.Fields[3].Comments[encoder.LineComment] = "Owner of this subent pool"
	SubnetPoolDoc.Fields[4].Name = "prefix"
	SubnetPoolDoc.Fields[4].Type = "string"
	SubnetPoolDoc.Fields[4].Note = ""
	SubnetPoolDoc.Fields[4].Description = "Prefix"
	SubnetPoolDoc.Fields[4].Comments[encoder.LineComment] = "Prefix"
	SubnetPoolDoc.Fields[5].Name = "label"
	SubnetPoolDoc.Fields[5].Type = "string"
	SubnetPoolDoc.Fields[5].Note = ""
	SubnetPoolDoc.Fields[5].Description = "Label of this subnet pool"
	SubnetPoolDoc.Fields[5].Comments[encoder.LineComment] = "Label of this subnet pool"
	SubnetPoolDoc.Fields[6].Name = "prefixHex"
	SubnetPoolDoc.Fields[6].Type = "string"
	SubnetPoolDoc.Fields[6].Note = ""
	SubnetPoolDoc.Fields[6].Description = "Internal"
	SubnetPoolDoc.Fields[6].Comments[encoder.LineComment] = "Internal"
	SubnetPoolDoc.Fields[7].Name = "netmask"
	SubnetPoolDoc.Fields[7].Type = "string"
	SubnetPoolDoc.Fields[7].Note = ""
	SubnetPoolDoc.Fields[7].Description = "Netmask"
	SubnetPoolDoc.Fields[7].Comments[encoder.LineComment] = "Netmask"
	SubnetPoolDoc.Fields[8].Name = "netmaskHex"
	SubnetPoolDoc.Fields[8].Type = "string"
	SubnetPoolDoc.Fields[8].Note = ""
	SubnetPoolDoc.Fields[8].Description = "Internal"
	SubnetPoolDoc.Fields[8].Comments[encoder.LineComment] = "Internal"
	SubnetPoolDoc.Fields[9].Name = "size"
	SubnetPoolDoc.Fields[9].Type = "int"
	SubnetPoolDoc.Fields[9].Note = ""
	SubnetPoolDoc.Fields[9].Description = "Size of the prefix"
	SubnetPoolDoc.Fields[9].Comments[encoder.LineComment] = "Size of the prefix"
	SubnetPoolDoc.Fields[10].Name = "type"
	SubnetPoolDoc.Fields[10].Type = "string"
	SubnetPoolDoc.Fields[10].Note = ""
	SubnetPoolDoc.Fields[10].Description = "Type"
	SubnetPoolDoc.Fields[10].Comments[encoder.LineComment] = "Type"
	SubnetPoolDoc.Fields[10].Values = []string{
		"ipv4",
		"ipv6",
	}
	SubnetPoolDoc.Fields[11].Name = "routable"
	SubnetPoolDoc.Fields[11].Type = "bool"
	SubnetPoolDoc.Fields[11].Note = ""
	SubnetPoolDoc.Fields[11].Description = "If set to true this subnet pool will be used for subnets that are routed (usually to the internet)"
	SubnetPoolDoc.Fields[11].Comments[encoder.LineComment] = "If set to true this subnet pool will be used for subnets that are routed (usually to the internet)"
	SubnetPoolDoc.Fields[12].Name = "destination"
	SubnetPoolDoc.Fields[12].Type = "string"
	SubnetPoolDoc.Fields[12].Note = ""
	SubnetPoolDoc.Fields[12].Description = "description: What this subnet is intended for:"
	SubnetPoolDoc.Fields[12].Comments[encoder.LineComment] = "description: What this subnet is intended for:"
	SubnetPoolDoc.Fields[12].Values = []string{
		"wan",
		"lan",
		"san",
		"oob",
		"quarantine",
		"loopback",
		"vtep",
		"disabled",
	}
	SubnetPoolDoc.Fields[13].Name = "currentUtilizationJSON"
	SubnetPoolDoc.Fields[13].Type = "string"
	SubnetPoolDoc.Fields[13].Note = ""
	SubnetPoolDoc.Fields[13].Description = "Internal"
	SubnetPoolDoc.Fields[13].Comments[encoder.LineComment] = "Internal"
	SubnetPoolDoc.Fields[14].Name = "currentUtilizationLastUpdated"
	SubnetPoolDoc.Fields[14].Type = "string"
	SubnetPoolDoc.Fields[14].Note = ""
	SubnetPoolDoc.Fields[14].Description = "Internal"
	SubnetPoolDoc.Fields[14].Comments[encoder.LineComment] = "Internal"
	SubnetPoolDoc.Fields[15].Name = "manualAllocationOnly"
	SubnetPoolDoc.Fields[15].Type = "bool"
	SubnetPoolDoc.Fields[15].Note = ""
	SubnetPoolDoc.Fields[15].Description = "If set to true this subnet will not be used for automatic allocation and will only be used in network profiles."
	SubnetPoolDoc.Fields[15].Comments[encoder.LineComment] = "If set to true this subnet will not be used for automatic allocation and will only be used in network profiles."

	SubnetPoolUtilizationDoc.Type = "SubnetPoolUtilization"
	SubnetPoolUtilizationDoc.Comments[encoder.LineComment] = "SubnetPoolUtilization describes the current utilization of the subnet"
	SubnetPoolUtilizationDoc.Description = "SubnetPoolUtilization describes the current utilization of the subnet"
	SubnetPoolUtilizationDoc.Fields = make([]encoder.Doc, 5)
	SubnetPoolUtilizationDoc.Fields[0].Name = "availableSubnets"
	SubnetPoolUtilizationDoc.Fields[0].Type = "map[string]int"
	SubnetPoolUtilizationDoc.Fields[0].Note = ""
	SubnetPoolUtilizationDoc.Fields[0].Description = "Count of available addresses"
	SubnetPoolUtilizationDoc.Fields[0].Comments[encoder.LineComment] = "Count of available addresses"
	SubnetPoolUtilizationDoc.Fields[1].Name = "allocatedSubnets"
	SubnetPoolUtilizationDoc.Fields[1].Type = "map[string]int"
	SubnetPoolUtilizationDoc.Fields[1].Note = ""
	SubnetPoolUtilizationDoc.Fields[1].Description = "Count of allocated addresses"
	SubnetPoolUtilizationDoc.Fields[1].Comments[encoder.LineComment] = "Count of allocated addresses"
	SubnetPoolUtilizationDoc.Fields[2].Name = "availableUsableIps"
	SubnetPoolUtilizationDoc.Fields[2].Type = "string"
	SubnetPoolUtilizationDoc.Fields[2].Note = ""
	SubnetPoolUtilizationDoc.Fields[2].Description = "Amount of usable addresses (excludes broadcast)"
	SubnetPoolUtilizationDoc.Fields[2].Comments[encoder.LineComment] = "Amount of usable addresses (excludes broadcast)"
	SubnetPoolUtilizationDoc.Fields[3].Name = "allocatedUsableIps"
	SubnetPoolUtilizationDoc.Fields[3].Type = "string"
	SubnetPoolUtilizationDoc.Fields[3].Note = ""
	SubnetPoolUtilizationDoc.Fields[3].Description = "Amount of allocated from the usable set"
	SubnetPoolUtilizationDoc.Fields[3].Comments[encoder.LineComment] = "Amount of allocated from the usable set"
	SubnetPoolUtilizationDoc.Fields[4].Name = "availablePercentage"
	SubnetPoolUtilizationDoc.Fields[4].Type = "string"
	SubnetPoolUtilizationDoc.Fields[4].Note = ""
	SubnetPoolUtilizationDoc.Fields[4].Description = "Available usable (Percentage)"
	SubnetPoolUtilizationDoc.Fields[4].Comments[encoder.LineComment] = "Available usable (Percentage)"
}

func (SubnetPool) Doc() *encoder.Doc {
	return &SubnetPoolDoc
}

func (SubnetPoolUtilization) Doc() *encoder.Doc {
	return &SubnetPoolUtilizationDoc
}

// GetSubnetPoolDoc returns documentation for the file ./.
func GetSubnetPoolDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "SubnetPool",
		Description: "",
		Structs: []*encoder.Doc{
			&SubnetPoolDoc,
			&SubnetPoolUtilizationDoc,
		},
	}
}
