// DO NOT EDIT: this file is automatically generated by docgen
package metalcloud

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var SwitchDeviceDoc encoder.Doc

func init() {
	SwitchDeviceDoc.Type = "SwitchDevice"
	SwitchDeviceDoc.Comments[encoder.LineComment] = "SwitchDevice Represents a switch installed in a datacenter."
	SwitchDeviceDoc.Description = "SwitchDevice Represents a switch installed in a datacenter."
	SwitchDeviceDoc.Fields = make([]encoder.Doc, 48)
	SwitchDeviceDoc.Fields[0].Name = "id"
	SwitchDeviceDoc.Fields[0].Type = "int"
	SwitchDeviceDoc.Fields[0].Note = ""
	SwitchDeviceDoc.Fields[0].Description = "id of the network equipment"
	SwitchDeviceDoc.Fields[0].Comments[encoder.LineComment] = "id of the network equipment"
	SwitchDeviceDoc.Fields[1].Name = "identifierString"
	SwitchDeviceDoc.Fields[1].Type = "string"
	SwitchDeviceDoc.Fields[1].Note = ""
	SwitchDeviceDoc.Fields[1].Description = "Hostname (or unique label) of the network equipment"
	SwitchDeviceDoc.Fields[1].Comments[encoder.LineComment] = "Hostname (or unique label) of the network equipment"
	SwitchDeviceDoc.Fields[2].Name = "datacenterName"
	SwitchDeviceDoc.Fields[2].Type = "string"
	SwitchDeviceDoc.Fields[2].Note = ""
	SwitchDeviceDoc.Fields[2].Description = "Datacenter"
	SwitchDeviceDoc.Fields[2].Comments[encoder.LineComment] = "Datacenter"
	SwitchDeviceDoc.Fields[3].Name = "provisionerType"
	SwitchDeviceDoc.Fields[3].Type = "string"
	SwitchDeviceDoc.Fields[3].Note = ""
	SwitchDeviceDoc.Fields[3].Description = "Type of provisioner. Read only"
	SwitchDeviceDoc.Fields[3].Comments[encoder.LineComment] = "Type of provisioner. Read only"
	SwitchDeviceDoc.Fields[3].Values = []string{
		"vpls",
		"vxlan",
		"vlan",
		"lan",
		"sdn",
		"evpnvxlanl2",
	}
	SwitchDeviceDoc.Fields[4].Name = "provisionerPosition"
	SwitchDeviceDoc.Fields[4].Type = "string"
	SwitchDeviceDoc.Fields[4].Note = ""
	SwitchDeviceDoc.Fields[4].Description = "Role of this equipment in the provisioner"
	SwitchDeviceDoc.Fields[4].Comments[encoder.LineComment] = "Role of this equipment in the provisioner"
	SwitchDeviceDoc.Fields[4].Values = []string{
		"tor",
		"north",
		"leaf",
		"spine",
		"other",
	}
	SwitchDeviceDoc.Fields[5].Name = "driver"
	SwitchDeviceDoc.Fields[5].Type = "string"
	SwitchDeviceDoc.Fields[5].Note = ""
	SwitchDeviceDoc.Fields[5].Description = "Driver to use. Note that this list may change frequently."
	SwitchDeviceDoc.Fields[5].Comments[encoder.LineComment] = "Driver to use. Note that this list may change frequently."
	SwitchDeviceDoc.Fields[5].Values = []string{
		"hp5800",
		"hp5900",
		"hp5950",
		"dell_s4000",
		"dell_s4048",
		"dell_s6010",
		"os_10",
		"cumulus42",
		"nexus9000",
		"cisco_aci51",
		"junos",
		"junos18",
		"sonic_enterprise",
		"dummy",
	}
	SwitchDeviceDoc.Fields[6].Name = "managementUsername"
	SwitchDeviceDoc.Fields[6].Type = "string"
	SwitchDeviceDoc.Fields[6].Note = ""
	SwitchDeviceDoc.Fields[6].Description = "Username"
	SwitchDeviceDoc.Fields[6].Comments[encoder.LineComment] = "Username"
	SwitchDeviceDoc.Fields[7].Name = "managementPassword"
	SwitchDeviceDoc.Fields[7].Type = "string"
	SwitchDeviceDoc.Fields[7].Note = ""
	SwitchDeviceDoc.Fields[7].Description = "Password"
	SwitchDeviceDoc.Fields[7].Comments[encoder.LineComment] = "Password"
	SwitchDeviceDoc.Fields[8].Name = "managementAddress"
	SwitchDeviceDoc.Fields[8].Type = "string"
	SwitchDeviceDoc.Fields[8].Note = ""
	SwitchDeviceDoc.Fields[8].Description = "Address"
	SwitchDeviceDoc.Fields[8].Comments[encoder.LineComment] = "Address"
	SwitchDeviceDoc.Fields[9].Name = "managementPort"
	SwitchDeviceDoc.Fields[9].Type = "int"
	SwitchDeviceDoc.Fields[9].Note = ""
	SwitchDeviceDoc.Fields[9].Description = "Port"
	SwitchDeviceDoc.Fields[9].Comments[encoder.LineComment] = "Port"
	SwitchDeviceDoc.Fields[10].Name = "managementProtocol"
	SwitchDeviceDoc.Fields[10].Type = "string"
	SwitchDeviceDoc.Fields[10].Note = ""
	SwitchDeviceDoc.Fields[10].Description = "Deprecated."
	SwitchDeviceDoc.Fields[10].Comments[encoder.LineComment] = "Deprecated."
	SwitchDeviceDoc.Fields[11].Name = "managementAddressMask"
	SwitchDeviceDoc.Fields[11].Type = "string"
	SwitchDeviceDoc.Fields[11].Note = ""
	SwitchDeviceDoc.Fields[11].Description = "Netmask of the management address"
	SwitchDeviceDoc.Fields[11].Comments[encoder.LineComment] = "Netmask of the management address"
	SwitchDeviceDoc.Fields[12].Name = "managementAddressGateway"
	SwitchDeviceDoc.Fields[12].Type = "string"
	SwitchDeviceDoc.Fields[12].Note = ""
	SwitchDeviceDoc.Fields[12].Description = "Gateway of the management address"
	SwitchDeviceDoc.Fields[12].Comments[encoder.LineComment] = "Gateway of the management address"
	SwitchDeviceDoc.Fields[13].Name = "managementMACAddress"
	SwitchDeviceDoc.Fields[13].Type = "string"
	SwitchDeviceDoc.Fields[13].Note = ""
	SwitchDeviceDoc.Fields[13].Description = "MAC address of the management address"
	SwitchDeviceDoc.Fields[13].Comments[encoder.LineComment] = "MAC address of the management address"
	SwitchDeviceDoc.Fields[14].Name = "primaryWANIPv4SubnetPool"
	SwitchDeviceDoc.Fields[14].Type = "string"
	SwitchDeviceDoc.Fields[14].Note = ""
	SwitchDeviceDoc.Fields[14].Description = "When set it will automatically create an IPv4 subnet pool for WAN. Deprecated"
	SwitchDeviceDoc.Fields[14].Comments[encoder.LineComment] = "When set it will automatically create an IPv4 subnet pool for WAN. Deprecated"
	SwitchDeviceDoc.Fields[15].Name = "primaryWANIPv4SubnetPrefixSize"
	SwitchDeviceDoc.Fields[15].Type = "int"
	SwitchDeviceDoc.Fields[15].Note = ""
	SwitchDeviceDoc.Fields[15].Description = "Size of the subnet pool to automatically create. Deprecated"
	SwitchDeviceDoc.Fields[15].Comments[encoder.LineComment] = "Size of the subnet pool to automatically create. Deprecated"
	SwitchDeviceDoc.Fields[16].Name = "primaryWANIPv6SubnetPool"
	SwitchDeviceDoc.Fields[16].Type = "string"
	SwitchDeviceDoc.Fields[16].Note = ""
	SwitchDeviceDoc.Fields[16].Description = "Label of an IPv6 subnet to use when creating the switch."
	SwitchDeviceDoc.Fields[16].Comments[encoder.LineComment] = "Label of an IPv6 subnet to use when creating the switch."
	SwitchDeviceDoc.Fields[17].Name = "primaryWANIPv6SubnetPoolID"
	SwitchDeviceDoc.Fields[17].Type = "int"
	SwitchDeviceDoc.Fields[17].Note = ""
	SwitchDeviceDoc.Fields[17].Description = "ID of an IPv6 subnet to use when creating the switch."
	SwitchDeviceDoc.Fields[17].Comments[encoder.LineComment] = "ID of an IPv6 subnet to use when creating the switch."
	SwitchDeviceDoc.Fields[18].Name = "primaryWANIPv6SubnetCIDR"
	SwitchDeviceDoc.Fields[18].Type = "string"
	SwitchDeviceDoc.Fields[18].Note = ""
	SwitchDeviceDoc.Fields[18].Description = "CIDR of the subnet to create a subnet pool with"
	SwitchDeviceDoc.Fields[18].Comments[encoder.LineComment] = "CIDR of the subnet to create a subnet pool with"
	SwitchDeviceDoc.Fields[19].Name = "primaryWANIPv6SubnetPrefixSize"
	SwitchDeviceDoc.Fields[19].Type = "int"
	SwitchDeviceDoc.Fields[19].Note = ""
	SwitchDeviceDoc.Fields[19].Description = "Size of the subnet"
	SwitchDeviceDoc.Fields[19].Comments[encoder.LineComment] = "Size of the subnet"
	SwitchDeviceDoc.Fields[20].Name = "primarySANSubnetPool"
	SwitchDeviceDoc.Fields[20].Type = "string"
	SwitchDeviceDoc.Fields[20].Note = ""
	SwitchDeviceDoc.Fields[20].Description = "Label of the SAN subnet to use"
	SwitchDeviceDoc.Fields[20].Comments[encoder.LineComment] = "Label of the SAN subnet to use"
	SwitchDeviceDoc.Fields[21].Name = "primarySANSubnetPrefixSize"
	SwitchDeviceDoc.Fields[21].Type = "int"
	SwitchDeviceDoc.Fields[21].Note = ""
	SwitchDeviceDoc.Fields[21].Description = "Size of the san subnet to use"
	SwitchDeviceDoc.Fields[21].Comments[encoder.LineComment] = "Size of the san subnet to use"
	SwitchDeviceDoc.Fields[22].Name = "quarantineSubnetStart"
	SwitchDeviceDoc.Fields[22].Type = "string"
	SwitchDeviceDoc.Fields[22].Note = ""
	SwitchDeviceDoc.Fields[22].Description = "Only used for legacy operation. Start of the quarantine subnet to use during provisioning."
	SwitchDeviceDoc.Fields[22].Comments[encoder.LineComment] = "Only used for legacy operation. Start of the quarantine subnet to use during provisioning."
	SwitchDeviceDoc.Fields[23].Name = "quarantineSubnetEnd"
	SwitchDeviceDoc.Fields[23].Type = "string"
	SwitchDeviceDoc.Fields[23].Note = ""
	SwitchDeviceDoc.Fields[23].Description = "Only used for legacy operation. End of the quarantine subnet to use during provisioning."
	SwitchDeviceDoc.Fields[23].Comments[encoder.LineComment] = "Only used for legacy operation. End of the quarantine subnet to use during provisioning."
	SwitchDeviceDoc.Fields[24].Name = "quarantineSubnetPrefixSize"
	SwitchDeviceDoc.Fields[24].Type = "int"
	SwitchDeviceDoc.Fields[24].Note = ""
	SwitchDeviceDoc.Fields[24].Description = "Only used for legacy operation. End of the quarantine subnet to use during provisioning."
	SwitchDeviceDoc.Fields[24].Comments[encoder.LineComment] = "Only used for legacy operation. End of the quarantine subnet to use during provisioning."
	SwitchDeviceDoc.Fields[25].Name = "quarantineSubnetGateway"
	SwitchDeviceDoc.Fields[25].Type = "string"
	SwitchDeviceDoc.Fields[25].Note = ""
	SwitchDeviceDoc.Fields[25].Description = "Only used for legacy operation. Gateway to use during provisioning."
	SwitchDeviceDoc.Fields[25].Comments[encoder.LineComment] = "Only used for legacy operation. Gateway to use during provisioning."
	SwitchDeviceDoc.Fields[26].Name = "description"
	SwitchDeviceDoc.Fields[26].Type = "string"
	SwitchDeviceDoc.Fields[26].Note = ""
	SwitchDeviceDoc.Fields[26].Description = "Description of the network equipment"
	SwitchDeviceDoc.Fields[26].Comments[encoder.LineComment] = "Description of the network equipment"
	SwitchDeviceDoc.Fields[27].Name = "country"
	SwitchDeviceDoc.Fields[27].Type = "string"
	SwitchDeviceDoc.Fields[27].Note = ""
	SwitchDeviceDoc.Fields[27].Description = "Location of the network equipment"
	SwitchDeviceDoc.Fields[27].Comments[encoder.LineComment] = "Location of the network equipment"
	SwitchDeviceDoc.Fields[28].Name = "city"
	SwitchDeviceDoc.Fields[28].Type = "string"
	SwitchDeviceDoc.Fields[28].Note = ""
	SwitchDeviceDoc.Fields[28].Description = "Location of the network equipment"
	SwitchDeviceDoc.Fields[28].Comments[encoder.LineComment] = "Location of the network equipment"
	SwitchDeviceDoc.Fields[29].Name = "netDatacenter"
	SwitchDeviceDoc.Fields[29].Type = "string"
	SwitchDeviceDoc.Fields[29].Note = ""
	SwitchDeviceDoc.Fields[29].Description = "Location of the network equipment"
	SwitchDeviceDoc.Fields[29].Comments[encoder.LineComment] = "Location of the network equipment"
	SwitchDeviceDoc.Fields[30].Name = "datacenterRoom"
	SwitchDeviceDoc.Fields[30].Type = "string"
	SwitchDeviceDoc.Fields[30].Note = ""
	SwitchDeviceDoc.Fields[30].Description = "Location of the network equipment"
	SwitchDeviceDoc.Fields[30].Comments[encoder.LineComment] = "Location of the network equipment"
	SwitchDeviceDoc.Fields[31].Name = "datacenterRack"
	SwitchDeviceDoc.Fields[31].Type = "string"
	SwitchDeviceDoc.Fields[31].Note = ""
	SwitchDeviceDoc.Fields[31].Description = "Location of the network equipment"
	SwitchDeviceDoc.Fields[31].Comments[encoder.LineComment] = "Location of the network equipment"
	SwitchDeviceDoc.Fields[32].Name = "rackPositionUpperUnit"
	SwitchDeviceDoc.Fields[32].Type = "int"
	SwitchDeviceDoc.Fields[32].Note = ""
	SwitchDeviceDoc.Fields[32].Description = "Location of the network equipment"
	SwitchDeviceDoc.Fields[32].Comments[encoder.LineComment] = "Location of the network equipment"
	SwitchDeviceDoc.Fields[33].Name = "rackPositionLowerUnit"
	SwitchDeviceDoc.Fields[33].Type = "int"
	SwitchDeviceDoc.Fields[33].Note = ""
	SwitchDeviceDoc.Fields[33].Description = "Location of the network equipment"
	SwitchDeviceDoc.Fields[33].Comments[encoder.LineComment] = "Location of the network equipment"
	SwitchDeviceDoc.Fields[34].Name = "serialNumber"
	SwitchDeviceDoc.Fields[34].Type = "string"
	SwitchDeviceDoc.Fields[34].Note = ""
	SwitchDeviceDoc.Fields[34].Description = "Serial number of the network equipment"
	SwitchDeviceDoc.Fields[34].Comments[encoder.LineComment] = "Serial number of the network equipment"
	SwitchDeviceDoc.Fields[35].Name = "chassisRackID"
	SwitchDeviceDoc.Fields[35].Type = "int"
	SwitchDeviceDoc.Fields[35].Note = ""
	SwitchDeviceDoc.Fields[35].Description = "If applicable the chassis id"
	SwitchDeviceDoc.Fields[35].Comments[encoder.LineComment] = "If applicable the chassis id"
	SwitchDeviceDoc.Fields[36].Name = "TORLinkedID"
	SwitchDeviceDoc.Fields[36].Type = "int"
	SwitchDeviceDoc.Fields[36].Note = ""
	SwitchDeviceDoc.Fields[36].Description = "If applicable, the id of the linked equipment"
	SwitchDeviceDoc.Fields[36].Comments[encoder.LineComment] = "If applicable, the id of the linked equipment"
	SwitchDeviceDoc.Fields[37].Name = "tags"
	SwitchDeviceDoc.Fields[37].Type = "[]string"
	SwitchDeviceDoc.Fields[37].Note = ""
	SwitchDeviceDoc.Fields[37].Description = "Tags"
	SwitchDeviceDoc.Fields[37].Comments[encoder.LineComment] = "Tags"
	SwitchDeviceDoc.Fields[38].Name = "requiresOSInstall"
	SwitchDeviceDoc.Fields[38].Type = "bool"
	SwitchDeviceDoc.Fields[38].Note = ""
	SwitchDeviceDoc.Fields[38].Description = "If set to true the OS will be reinstalled upon reboot"
	SwitchDeviceDoc.Fields[38].Comments[encoder.LineComment] = "If set to true the OS will be reinstalled upon reboot"
	SwitchDeviceDoc.Fields[39].Name = "isBorderDevice"
	SwitchDeviceDoc.Fields[39].Type = "bool"
	SwitchDeviceDoc.Fields[39].Note = ""
	SwitchDeviceDoc.Fields[39].Description = "If set to true this network equipment can be used for external connections"
	SwitchDeviceDoc.Fields[39].Comments[encoder.LineComment] = "If set to true this network equipment can be used for external connections"
	SwitchDeviceDoc.Fields[40].Name = "isStorageSwitch"
	SwitchDeviceDoc.Fields[40].Type = "bool"
	SwitchDeviceDoc.Fields[40].Note = ""
	SwitchDeviceDoc.Fields[40].Description = "If set to true this network equipment can be used for SAN fabrics"
	SwitchDeviceDoc.Fields[40].Comments[encoder.LineComment] = "If set to true this network equipment can be used for SAN fabrics"
	SwitchDeviceDoc.Fields[41].Name = "isGateway"
	SwitchDeviceDoc.Fields[41].Type = "bool"
	SwitchDeviceDoc.Fields[41].Note = ""
	SwitchDeviceDoc.Fields[41].Description = "In certain situations (such as for the VPLS provisioner) a switch can be used as a router"
	SwitchDeviceDoc.Fields[41].Comments[encoder.LineComment] = "In certain situations (such as for the VPLS provisioner) a switch can be used as a router"
	SwitchDeviceDoc.Fields[42].Name = "networkTypesAllowed"
	SwitchDeviceDoc.Fields[42].Type = "[]string"
	SwitchDeviceDoc.Fields[42].Note = ""
	SwitchDeviceDoc.Fields[42].Description = "Types of networks allowed on this switch"
	SwitchDeviceDoc.Fields[42].Comments[encoder.LineComment] = "Types of networks allowed on this switch"
	SwitchDeviceDoc.Fields[42].Values = []string{
		"wan",
		"lan",
		"san",
	}
	SwitchDeviceDoc.Fields[43].Name = "volumeTemplateID"
	SwitchDeviceDoc.Fields[43].Type = "int"
	SwitchDeviceDoc.Fields[43].Note = ""
	SwitchDeviceDoc.Fields[43].Description = "Template id of the NOS to be installed"
	SwitchDeviceDoc.Fields[43].Comments[encoder.LineComment] = "Template id of the NOS to be installed"
	SwitchDeviceDoc.Fields[44].Name = "LoopbackAddress"
	SwitchDeviceDoc.Fields[44].Type = "string"
	SwitchDeviceDoc.Fields[44].Note = ""
	SwitchDeviceDoc.Fields[44].Description = "Address of a loopback interface (if applicable)"
	SwitchDeviceDoc.Fields[44].Comments[encoder.LineComment] = "Address of a loopback interface (if applicable)"
	SwitchDeviceDoc.Fields[45].Name = "VTEPAddress"
	SwitchDeviceDoc.Fields[45].Type = "string"
	SwitchDeviceDoc.Fields[45].Note = ""
	SwitchDeviceDoc.Fields[45].Description = "Address of a VTEP"
	SwitchDeviceDoc.Fields[45].Comments[encoder.LineComment] = "Address of a VTEP"
	SwitchDeviceDoc.Fields[46].Name = "ASN"
	SwitchDeviceDoc.Fields[46].Type = "int"
	SwitchDeviceDoc.Fields[46].Note = ""
	SwitchDeviceDoc.Fields[46].Description = "Address of an ASN"
	SwitchDeviceDoc.Fields[46].Comments[encoder.LineComment] = "Address of an ASN"
	SwitchDeviceDoc.Fields[47].Name = "controllerID"
	SwitchDeviceDoc.Fields[47].Type = "int"
	SwitchDeviceDoc.Fields[47].Note = ""
	SwitchDeviceDoc.Fields[47].Description = "In the SDN provisioner the ID of the controller device"
	SwitchDeviceDoc.Fields[47].Comments[encoder.LineComment] = "In the SDN provisioner the ID of the controller device"
}

func (SwitchDevice) Doc() *encoder.Doc {
	return &SwitchDeviceDoc
}

// GetSwitchDeviceDoc returns documentation for the file ./.
func GetSwitchDeviceDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "SwitchDevice",
		Description: "",
		Structs: []*encoder.Doc{
			&SwitchDeviceDoc,
		},
	}
}
