// DO NOT EDIT: this file is automatically generated by docgen
package metalcloud

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var VariableDoc encoder.Doc

func init() {
	VariableDoc.Type = "Variable"
	VariableDoc.Comments[encoder.LineComment] = "Variable struct defines a Variable type"
	VariableDoc.Description = "Variable struct defines a Variable type"
	VariableDoc.Fields = make([]encoder.Doc, 8)
	VariableDoc.Fields[0].Name = "id"
	VariableDoc.Fields[0].Type = "int"
	VariableDoc.Fields[0].Note = ""
	VariableDoc.Fields[0].Description = "The id of the object"
	VariableDoc.Fields[0].Comments[encoder.LineComment] = "The id of the object"
	VariableDoc.Fields[1].Name = "ownerID"
	VariableDoc.Fields[1].Type = "int"
	VariableDoc.Fields[1].Note = ""
	VariableDoc.Fields[1].Description = "The id of the owner (user object) of the object"
	VariableDoc.Fields[1].Comments[encoder.LineComment] = "The id of the owner (user object) of the object"
	VariableDoc.Fields[2].Name = "userIDAuthenticated"
	VariableDoc.Fields[2].Type = "int"
	VariableDoc.Fields[2].Note = ""
	VariableDoc.Fields[2].Description = "The id of the user that is currently manipulating the object. Readonly."
	VariableDoc.Fields[2].Comments[encoder.LineComment] = "The id of the user that is currently manipulating the object. Readonly."
	VariableDoc.Fields[3].Name = "name"
	VariableDoc.Fields[3].Type = "string"
	VariableDoc.Fields[3].Note = ""
	VariableDoc.Fields[3].Description = "The name of the variable"
	VariableDoc.Fields[3].Comments[encoder.LineComment] = "The name of the variable"
	VariableDoc.Fields[4].Name = "usage"
	VariableDoc.Fields[4].Type = "string"
	VariableDoc.Fields[4].Note = ""
	VariableDoc.Fields[4].Description = "The usage of a variable"
	VariableDoc.Fields[4].Comments[encoder.LineComment] = "The usage of a variable"
	VariableDoc.Fields[5].Name = "json"
	VariableDoc.Fields[5].Type = "string"
	VariableDoc.Fields[5].Note = ""
	VariableDoc.Fields[5].Description = "The content of the variable in json encoded format"
	VariableDoc.Fields[5].Comments[encoder.LineComment] = "The content of the variable in json encoded format"
	VariableDoc.Fields[6].Name = "createdTimestamp"
	VariableDoc.Fields[6].Type = "string"
	VariableDoc.Fields[6].Note = ""
	VariableDoc.Fields[6].Description = "Timestamp of the variable creation date. Readonly"
	VariableDoc.Fields[6].Comments[encoder.LineComment] = "Timestamp of the variable creation date. Readonly"
	VariableDoc.Fields[7].Name = "updatedTimestamp"
	VariableDoc.Fields[7].Type = "string"
	VariableDoc.Fields[7].Note = ""
	VariableDoc.Fields[7].Description = "Timestamp of the variable last update. Readonly"
	VariableDoc.Fields[7].Comments[encoder.LineComment] = "Timestamp of the variable last update. Readonly"
}

func (Variable) Doc() *encoder.Doc {
	return &VariableDoc
}

// GetVariableDoc returns documentation for the file ./.
func GetVariableDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "Variable",
		Description: "",
		Structs: []*encoder.Doc{
			&VariableDoc,
		},
	}
}
