// DO NOT EDIT: this file is automatically generated by docgen
package metalcloud

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var (
	WorkflowDoc                         encoder.Doc
	WorkflowStageDefinitionReferenceDoc encoder.Doc
	WorkflowStageAssociationDoc         encoder.Doc
)

func init() {
	WorkflowDoc.Type = "Workflow"
	WorkflowDoc.Comments[encoder.LineComment] = "Workflow struct defines a server type"
	WorkflowDoc.Description = "Workflow struct defines a server type"
	WorkflowDoc.Fields = make([]encoder.Doc, 11)
	WorkflowDoc.Fields[0].Name = "id"
	WorkflowDoc.Fields[0].Type = "int"
	WorkflowDoc.Fields[0].Note = ""
	WorkflowDoc.Fields[0].Description = "Id of the object"
	WorkflowDoc.Fields[0].Comments[encoder.LineComment] = "Id of the object"
	WorkflowDoc.Fields[1].Name = "ownerID"
	WorkflowDoc.Fields[1].Type = "int"
	WorkflowDoc.Fields[1].Note = ""
	WorkflowDoc.Fields[1].Description = "Id of the owner"
	WorkflowDoc.Fields[1].Comments[encoder.LineComment] = "Id of the owner"
	WorkflowDoc.Fields[2].Name = "userIDAuthenticated"
	WorkflowDoc.Fields[2].Type = "int"
	WorkflowDoc.Fields[2].Note = ""
	WorkflowDoc.Fields[2].Description = "Internal."
	WorkflowDoc.Fields[2].Comments[encoder.LineComment] = "Internal."
	WorkflowDoc.Fields[3].Name = "label"
	WorkflowDoc.Fields[3].Type = "string"
	WorkflowDoc.Fields[3].Note = ""
	WorkflowDoc.Fields[3].Description = "Label"
	WorkflowDoc.Fields[3].Comments[encoder.LineComment] = "Label"
	WorkflowDoc.Fields[4].Name = "usage"
	WorkflowDoc.Fields[4].Type = "string"
	WorkflowDoc.Fields[4].Note = ""
	WorkflowDoc.Fields[4].Description = "Usage of this workflow"
	WorkflowDoc.Fields[4].Comments[encoder.LineComment] = "Usage of this workflow"
	WorkflowDoc.Fields[4].Values = []string{
		"infrastructure",
		"switch_device",
		"server",
		"free_standing",
		"storage_pool",
		"user",
		"os_template",
		"global",
	}
	WorkflowDoc.Fields[5].Name = "title"
	WorkflowDoc.Fields[5].Type = "string"
	WorkflowDoc.Fields[5].Note = ""
	WorkflowDoc.Fields[5].Description = "Title (name) of this workflow"
	WorkflowDoc.Fields[5].Comments[encoder.LineComment] = "Title (name) of this workflow"
	WorkflowDoc.Fields[6].Name = "description"
	WorkflowDoc.Fields[6].Type = "string"
	WorkflowDoc.Fields[6].Note = ""
	WorkflowDoc.Fields[6].Description = "Description of this workflow"
	WorkflowDoc.Fields[6].Comments[encoder.LineComment] = "Description of this workflow"
	WorkflowDoc.Fields[7].Name = "isDeprecated"
	WorkflowDoc.Fields[7].Type = "bool"
	WorkflowDoc.Fields[7].Note = ""
	WorkflowDoc.Fields[7].Description = "Set to true if this workflow is deprecated"
	WorkflowDoc.Fields[7].Comments[encoder.LineComment] = "Set to true if this workflow is deprecated"
	WorkflowDoc.Fields[8].Name = "assetDataURI"
	WorkflowDoc.Fields[8].Type = "string"
	WorkflowDoc.Fields[8].Note = ""
	WorkflowDoc.Fields[8].Description = "Internal"
	WorkflowDoc.Fields[8].Comments[encoder.LineComment] = "Internal"
	WorkflowDoc.Fields[9].Name = "createdTimestamp"
	WorkflowDoc.Fields[9].Type = "string"
	WorkflowDoc.Fields[9].Note = ""
	WorkflowDoc.Fields[9].Description = "ISO 8601 timestamp which holds the date and time when the workflow record was created. Readonly."
	WorkflowDoc.Fields[9].Comments[encoder.LineComment] = "ISO 8601 timestamp which holds the date and time when the workflow record was created. Readonly."
	WorkflowDoc.Fields[10].Name = "updatedTimestamp"
	WorkflowDoc.Fields[10].Type = "string"
	WorkflowDoc.Fields[10].Note = ""
	WorkflowDoc.Fields[10].Description = "ISO 8601 timestamp which holds the date and time when the workflow record was updated. Readonly."
	WorkflowDoc.Fields[10].Comments[encoder.LineComment] = "ISO 8601 timestamp which holds the date and time when the workflow record was updated. Readonly."

	WorkflowStageDefinitionReferenceDoc.Type = "WorkflowStageDefinitionReference"
	WorkflowStageDefinitionReferenceDoc.Comments[encoder.LineComment] = "WorkflowStageDefinitionReference defines where in a workflow a stage definition resides"
	WorkflowStageDefinitionReferenceDoc.Description = "WorkflowStageDefinitionReference defines where in a workflow a stage definition resides"
	WorkflowStageDefinitionReferenceDoc.Fields = make([]encoder.Doc, 4)
	WorkflowStageDefinitionReferenceDoc.Fields[0].Name = "workflowStageID"
	WorkflowStageDefinitionReferenceDoc.Fields[0].Type = "int"
	WorkflowStageDefinitionReferenceDoc.Fields[0].Note = ""
	WorkflowStageDefinitionReferenceDoc.Fields[0].Description = "Workflow stage id"
	WorkflowStageDefinitionReferenceDoc.Fields[0].Comments[encoder.LineComment] = "Workflow stage id"
	WorkflowStageDefinitionReferenceDoc.Fields[1].Name = "workflowID"
	WorkflowStageDefinitionReferenceDoc.Fields[1].Type = "int"
	WorkflowStageDefinitionReferenceDoc.Fields[1].Note = ""
	WorkflowStageDefinitionReferenceDoc.Fields[1].Description = "Workflow id"
	WorkflowStageDefinitionReferenceDoc.Fields[1].Comments[encoder.LineComment] = "Workflow id"
	WorkflowStageDefinitionReferenceDoc.Fields[2].Name = "stageDefinitionID"
	WorkflowStageDefinitionReferenceDoc.Fields[2].Type = "int"
	WorkflowStageDefinitionReferenceDoc.Fields[2].Note = ""
	WorkflowStageDefinitionReferenceDoc.Fields[2].Description = "Stage definition id"
	WorkflowStageDefinitionReferenceDoc.Fields[2].Comments[encoder.LineComment] = "Stage definition id"
	WorkflowStageDefinitionReferenceDoc.Fields[3].Name = "runLevel"
	WorkflowStageDefinitionReferenceDoc.Fields[3].Type = "int"
	WorkflowStageDefinitionReferenceDoc.Fields[3].Note = ""
	WorkflowStageDefinitionReferenceDoc.Fields[3].Description = "Run level in the workflow"
	WorkflowStageDefinitionReferenceDoc.Fields[3].Comments[encoder.LineComment] = "Run level in the workflow"

	WorkflowStageAssociationDoc.Type = "WorkflowStageAssociation"
	WorkflowStageAssociationDoc.Comments[encoder.LineComment] = "WorkflowStageAssociation associations"
	WorkflowStageAssociationDoc.Description = "WorkflowStageAssociation associations"
	WorkflowStageAssociationDoc.Fields = make([]encoder.Doc, 6)
	WorkflowStageAssociationDoc.Fields[0].Name = "infrastructureDeployStageID"
	WorkflowStageAssociationDoc.Fields[0].Type = "int"
	WorkflowStageAssociationDoc.Fields[0].Note = ""
	WorkflowStageAssociationDoc.Fields[0].Description = "Infrastructure stage id"
	WorkflowStageAssociationDoc.Fields[0].Comments[encoder.LineComment] = "Infrastructure stage id"
	WorkflowStageAssociationDoc.Fields[1].Name = "infrastructureID"
	WorkflowStageAssociationDoc.Fields[1].Type = "int"
	WorkflowStageAssociationDoc.Fields[1].Note = ""
	WorkflowStageAssociationDoc.Fields[1].Description = "Infrastructure id"
	WorkflowStageAssociationDoc.Fields[1].Comments[encoder.LineComment] = "Infrastructure id"
	WorkflowStageAssociationDoc.Fields[2].Name = "definitionID"
	WorkflowStageAssociationDoc.Fields[2].Type = "int"
	WorkflowStageAssociationDoc.Fields[2].Note = ""
	WorkflowStageAssociationDoc.Fields[2].Description = "Stage definition id"
	WorkflowStageAssociationDoc.Fields[2].Comments[encoder.LineComment] = "Stage definition id"
	WorkflowStageAssociationDoc.Fields[3].Name = "type"
	WorkflowStageAssociationDoc.Fields[3].Type = "string"
	WorkflowStageAssociationDoc.Fields[3].Note = ""
	WorkflowStageAssociationDoc.Fields[3].Description = "description: Type of position in the infrastructure:"
	WorkflowStageAssociationDoc.Fields[3].Comments[encoder.LineComment] = "description: Type of position in the infrastructure:"
	WorkflowStageAssociationDoc.Fields[3].Values = []string{
		"pre_deploy",
		"post_deploy",
	}
	WorkflowStageAssociationDoc.Fields[4].Name = "runLevel"
	WorkflowStageAssociationDoc.Fields[4].Type = "int"
	WorkflowStageAssociationDoc.Fields[4].Note = ""
	WorkflowStageAssociationDoc.Fields[4].Description = "Run level (the depth in the tree where this stage resides)."
	WorkflowStageAssociationDoc.Fields[4].Comments[encoder.LineComment] = "Run level (the depth in the tree where this stage resides)."
	WorkflowStageAssociationDoc.Fields[5].Name = "lastOutput"
	WorkflowStageAssociationDoc.Fields[5].Type = "string"
	WorkflowStageAssociationDoc.Fields[5].Note = ""
	WorkflowStageAssociationDoc.Fields[5].Description = "The output of the last execution of this task"
	WorkflowStageAssociationDoc.Fields[5].Comments[encoder.LineComment] = "The output of the last execution of this task"
}

func (Workflow) Doc() *encoder.Doc {
	return &WorkflowDoc
}

func (WorkflowStageDefinitionReference) Doc() *encoder.Doc {
	return &WorkflowStageDefinitionReferenceDoc
}

func (WorkflowStageAssociation) Doc() *encoder.Doc {
	return &WorkflowStageAssociationDoc
}

// GetWorkflowDoc returns documentation for the file ./.
func GetWorkflowDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "Workflow",
		Description: "",
		Structs: []*encoder.Doc{
			&WorkflowDoc,
			&WorkflowStageDefinitionReferenceDoc,
			&WorkflowStageAssociationDoc,
		},
	}
}
